import type {IdSistema} from '../anatomia.ts';
import type { ConceitoIndexado, IdRegiaoAnatomica } from './catalogo-anatomico.ts';

export type TipoFichaDetalhada = 'marco-clinico' | 'correlacao-cirurgica' | 'revisao-organica';


export interface FichaEstudoDetalhado {
  id: string;
  titulo: string;
  tipo: TipoFichaDetalhada;
  sistema?: IdSistema;
  regiao?: IdRegiaoAnatomica;
  resumo: string;
  visualizacao: string;
  gatilhos: string[];
  estruturasChave: string[];
  pontosResidencia: string[];
  limites?: string[];
  conteudo?: string[];
  camadas?: string[];
  clinica?: string[];
  lacunasModelo?: string[];
}

export interface FichaEstudoResolvida extends FichaEstudoDetalhado {
  conceitosRelacionados: ConceitoIndexado[];
}

function normalizar(texto: string): string {
  return texto
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

function chaveBusca(item: ConceitoIndexado): string {
  return normalizar([
    item.conceito.id,
    item.conceito.nome,
    item.conceito.nomeOriginal,
    ...item.aliases,
  ].filter(Boolean).join(' '));
}

function localizarConceitos(indice: ConceitoIndexado[], termos: string[]): ConceitoIndexado[] {
  const encontrados = new Map<string, ConceitoIndexado>();
  const normalizados = termos.map(normalizar).filter(Boolean);

  normalizados.forEach((termo) => {
    indice
      .filter((item) => chaveBusca(item).includes(termo))
      .sort((a, b) => a.conceito.nome.localeCompare(b.conceito.nome, 'pt-BR'))
      .forEach((item) => {
        if (!encontrados.has(item.conceito.id)) encontrados.set(item.conceito.id, item);
      });
  });

  return [...encontrados.values()];
}

/**
 * Biblioteca de marcos anatômicos de prova.
 *
 * A proposta aqui é didática: cada ficha aproxima estruturas clássicas de prova
 * das peças realmente disponíveis no atlas 3D. Quando a malha exata não existe,
 * a ficha informa a limitação e sugere o melhor contexto visual possível.
 */
export const FICHAS_ESTUDO_DETALHADO: FichaEstudoDetalhado[] = [

  {
    id: 'circulo-willis',
    titulo: 'Círculo arterial cerebral (de Willis)',
    tipo: 'marco-clinico',
    sistema: 'arterial',
    regiao: 'cabeca',
    resumo: 'Anel arterial da base do encéfalo, essencial para circulação colateral e para provas de neurovascular.',
    visualizacao: 'No crânio, selecione as artérias cerebrais e carótidas internas para revisar o anel arterial e suas comunicações.',
    gatilhos: ['willis', 'círculo arterial cerebral', 'circulo arterial cerebral', 'artéria cerebral', 'carótida interna', 'comunicante'],
    estruturasChave: ['cerebral arterial círculo', 'artéria cerebral anterior', 'artéria comunicante anterior', 'artéria comunicante posterior', 'artéria carótida interna', 'artéria cerebral posterior'],
    conteudo: ['Carótidas internas.', 'Artérias cerebrais anteriores.', 'Artéria comunicante anterior.', 'Artérias comunicantes posteriores.', 'Segmentos proximais das artérias cerebrais posteriores.'],
    pontosResidencia: ['Aneurismas saculares costumam aparecer nas junções arteriais do círculo.', 'A circulação colateral ajuda a explicar déficits variáveis em obstruções proximais.'],
    clinica: ['Tema clássico em neurologia, neurocirurgia e emergência neurológica.'],
  },
  {
    id: 'sistema-carotideo-cervical',
    titulo: 'Sistema carotídeo cervical',
    tipo: 'revisao-organica',
    sistema: 'arterial',
    regiao: 'pescoco',
    resumo: 'Revisão dos vasos cervicais anteriores, importante para semiologia, cirurgia e imagem.',
    visualizacao: 'Selecione a artéria carótida interna e explore suas relações com tireoide, laringe e traqueia no pescoço.',
    gatilhos: ['carótida', 'carotida', 'carótida interna', 'carótida comum', 'pescoço'],
    estruturasChave: ['artéria carótida interna', 'tireoide', 'laringe', 'traqueia'],
    conteudo: ['Carótida interna.', 'Trajeto cervical anterior.', 'Relações com vísceras cervicais.'],
    pontosResidencia: ['A bifurcação carotídea e o seio carotídeo têm relevância clínica recorrente.', 'Relações cervicais são muito cobradas em procedimentos e em cirurgia de cabeça e pescoço.'],
    lacunasModelo: ['A carótida comum e alguns nervos cervicais não aparecem sempre como malhas isoladas; o atlas enfatiza o contexto vascular e visceral disponível.'],
  },
  {
    id: 'orbita-musculos-oculares',
    titulo: 'Órbita e músculos extrínsecos do olho',
    tipo: 'revisao-organica',
    sistema: 'muscular',
    regiao: 'cabeca',
    resumo: 'Bloco de alta utilidade para revisão de motricidade ocular e estrabismos.',
    visualizacao: 'Selecione o olho e depois destaque os músculos retos superior, inferior, medial e lateral para estudar os vetores de movimento.',
    gatilhos: ['órbita', 'orbita', 'olho', 'globo ocular', 'reto superior', 'reto medial', 'reto lateral'],
    estruturasChave: ['olho do lado direito', 'globo ocular do lado direito', 'superior reto', 'inferior reto', 'medial reto', 'lateral reto'],
    conteudo: ['Globo ocular.', 'Músculos retos.', 'Organização orbital básica.'],
    pontosResidencia: ['Reto lateral abduz o olho; reto medial aduz.', 'Reto superior e inferior têm ações combinadas e costumam aparecer em correlações neuroftalmológicas.'],
    clinica: ['Útil em neuroanatomia, oftalmologia e propedêutica neurológica.'],
  },
  {
    id: 'nervo-optico-orbita',
    titulo: 'Nervo óptico e via orbitária',
    tipo: 'marco-clinico',
    sistema: 'nervoso',
    regiao: 'cabeca',
    resumo: 'Revisão orientada do nervo óptico no contexto da órbita.',
    visualizacao: 'Selecione o nervo óptico e o globo ocular para revisar sua continuidade anatômica dentro da órbita.',
    gatilhos: ['nervo óptico', 'nervo optico', 'órbita', 'orbita', 'olho'],
    estruturasChave: ['nervo óptico', 'globo ocular do lado direito', 'globo ocular do lado esquerdo', 'olho do lado direito', 'olho do lado esquerdo'],
    conteudo: ['Nervo óptico.', 'Globo ocular.', 'Região orbital.'],
    pontosResidencia: ['A aferência do reflexo fotomotor depende do nervo óptico.', 'Comprimé-lo pode causar perda visual e defeitos pupilares aferentes.'],
    clinica: ['Muito cobrado em neuroftalmologia e síndromes compressivas orbitárias.'],
  },
  {
    id: 'laringe-faringe-traqueia',
    titulo: 'Faringe, laringe e traqueia',
    tipo: 'revisao-organica',
    sistema: 'respiratorio',
    regiao: 'pescoco',
    resumo: 'Eixo aerodigestivo superior fundamental para intubação, via aérea e anatomia cervical.',
    visualizacao: 'Selecione traqueia, laringe e faringe para entender a continuidade anatômica do pescoço à cavidade torácica.',
    gatilhos: ['faringe', 'laringe', 'traqueia', 'via aérea', 'via aerea'],
    estruturasChave: ['faringe', 'laringe', 'traqueia', 'esôfago'],
    conteudo: ['Faringe.', 'Laringe.', 'Traqueia.', 'Esôfago como relação posterior.'],
    pontosResidencia: ['A traqueia fica anterior ao esôfago.', 'Laringe e faringe aparecem frequentemente em questões de via aérea difícil e aspiração.'],
    clinica: ['Base para anestesia, otorrino e urgência.'],
  },
  {
    id: 'tireoide-regiao-anterior-pescoco',
    titulo: 'Tireoide e região anterior do pescoço',
    tipo: 'revisao-organica',
    sistema: 'endocrino',
    regiao: 'pescoco',
    resumo: 'Revisão da glândula tireoide e de suas relações cervicais anteriores.',
    visualizacao: 'Use a tireoide com laringe e traqueia para estudar topografia cirúrgica do pescoço anterior.',
    gatilhos: ['tireoide', 'tireóide', 'thyroid', 'pescoço anterior'],
    estruturasChave: ['tireoide', 'artéria tireoide inferior', 'laringe', 'traqueia'],
    conteudo: ['Glândula tireoide.', 'Relação com traqueia e laringe.', 'Vascularização cervical inferior.'],
    pontosResidencia: ['Em tireoidectomia, as relações vasculares e nervosas são centrais.', 'Bócio e massas cervicais alteram a anatomia de superfície.'],
    lacunasModelo: ['Alguns nervos laríngeos e parte da vascularização superior podem não aparecer isoladamente.'],
  },
  {
    id: 'hipofise-regiao-selar',
    titulo: 'Hipófise e região selar',
    tipo: 'marco-clinico',
    sistema: 'endocrino',
    regiao: 'cabeca',
    resumo: 'Estrutura-chave em neuroendócrino e em correlações com quiasma óptico.',
    visualizacao: 'Selecione a hipófise e estude-a em conjunto com o contexto craniano e orbital.',
    gatilhos: ['hipófise', 'hipofise', 'pituitary', 'sela'],
    estruturasChave: ['hipófise', 'nervo óptico'],
    conteudo: ['Hipófise.', 'Correlação com via óptica anterior.'],
    pontosResidencia: ['Macroadenomas hipofisários podem cursar com alterações campimétricas.', 'É tema comum em endocrinologia e neurocirurgia.'],
    lacunasModelo: ['A sela túrcica, o quiasma óptico e a vascularização hipofisária não estão integralmente segmentados como malhas dedicadas.'],
  },
  {
    id: 'mandibula-maxila-zigomatico',
    titulo: 'Mandíbula, maxila e arco zigomático',
    tipo: 'revisao-organica',
    sistema: 'esqueletico',
    regiao: 'cabeca',
    resumo: 'Revisão óssea essencial para trauma de face e odontologia.',
    visualizacao: 'Selecione mandíbula, maxila e osso zigomático para revisar a arquitetura básica da face.',
    gatilhos: ['mandíbula', 'mandibula', 'maxila', 'zigomático', 'zigomatico', 'face'],
    estruturasChave: ['mandíbula', 'maxila', 'osso zigomático'],
    conteudo: ['Mandíbula.', 'Maxila.', 'Complexo zigomático.'],
    pontosResidencia: ['Fraturas mandibulares e zigomáticas são clássicas em trauma.', 'A maxila participa do terço médio da face e se relaciona com órbita e cavidade oral.'],
    clinica: ['Alta utilidade em cirurgia bucomaxilofacial e pronto-socorro.'],
  },
  {
    id: 'coracao-grandes-vasos',
    titulo: 'Coração e grandes vasos',
    tipo: 'revisao-organica',
    sistema: 'cardiaco',
    regiao: 'torax',
    resumo: 'Rota de estudo do coração associando o órgão às vias de entrada e saída do sangue.',
    visualizacao: 'Selecione o coração e mostre as estruturas relacionadas para revisar aorta, veia cava superior, veia cava inferior e artéria pulmonar.',
    gatilhos: ['coração', 'coracao', 'aorta', 'veia cava', 'artéria pulmonar', 'grandes vasos'],
    estruturasChave: ['coração', 'aorta', 'veia cava superior', 'veia cava inferior', 'artéria pulmonar'],
    pontosResidencia: ['Direito: recebe sangue venoso e o envia ao pulmão.', 'Esquerdo: recebe sangue oxigenado e o envia à circulação sistêmica.', 'Aorta ascendente, arco e aorta descendente aparecem em sequência frequente em prova.'],
    clinica: ['Base para interpretação de insuficiências valvares, choque e anatomia de imagem.'],
  },
  {
    id: 'circulacao-coronaria',
    titulo: 'Circulação coronária',
    tipo: 'marco-clinico',
    sistema: 'arterial',
    regiao: 'torax',
    resumo: 'Revisão de vasos coronários aplicada a síndromes coronarianas e anatomia do coração.',
    visualizacao: 'Com o coração selecionado, procure ramos coronários para revisar irrigação epicárdica.',
    gatilhos: ['coronária', 'coronaria', 'coronary', 'coração'],
    estruturasChave: ['coração', 'tronco da artéria coronária do lado direito'],
    conteudo: ['Artérias coronárias epicárdicas.', 'Ramos ventriculares e atriais quando presentes.'],
    pontosResidencia: ['Territórios coronarianos ajudam a explicar localizações de infarto.', 'Dominância coronária é conceito frequentemente cobrado.'],
    lacunasModelo: ['A árvore coronária está disponível de forma parcial e com variabilidade de ramos nomeados; use o guia como reforço visual, não como mapa cirúrgico definitivo.'],
  },
  {
    id: 'mediastino-superior',
    titulo: 'Mediastino superior',
    tipo: 'revisao-organica',
    sistema: 'respiratorio',
    regiao: 'torax',
    resumo: 'Organização das grandes estruturas centrais do tórax.',
    visualizacao: 'Use traqueia, esôfago, arco da aorta, veia cava superior e timo para revisar o mediastino superior.',
    gatilhos: ['mediastino', 'traqueia', 'esôfago', 'arco da aorta', 'timo'],
    estruturasChave: ['traqueia', 'esôfago', 'arco da aorta', 'veia cava superior', 'lobo do timo'],
    conteudo: ['Traqueia.', 'Esôfago.', 'Grandes vasos.', 'Timo.'],
    pontosResidencia: ['A traqueia fica anterior ao esôfago.', 'Massas do mediastino superior alteram relações vasculares e de via aérea.'],
    clinica: ['Útil em radiologia e cirurgia torácica.'],
  },
  {
    id: 'aorta-toracica',
    titulo: 'Aorta torácica',
    tipo: 'revisao-organica',
    sistema: 'arterial',
    regiao: 'torax',
    resumo: 'Percurso da aorta da sua porção ascendente até a descendente torácica.',
    visualizacao: 'Selecione a aorta e navegue entre aorta ascendente, arco e aorta descendente.',
    gatilhos: ['aorta', 'arco da aorta', 'torácica', 'toracica'],
    estruturasChave: ['aorta', 'ascendente aorta', 'arco da aorta', 'descendente torácico aorta'],
    conteudo: ['Aorta ascendente.', 'Arco da aorta.', 'Aorta torácica descendente.'],
    pontosResidencia: ['Aneurismas e dissecções são vinculados à topografia da aorta.', 'O arco da aorta é um marco obrigatório de prova.'],
  },
  {
    id: 'sistema-azigos',
    titulo: 'Sistema ázigos',
    tipo: 'revisao-organica',
    sistema: 'venoso',
    regiao: 'torax',
    resumo: 'Sistema venoso de drenagem torácica posterior com importância clínica e radiológica.',
    visualizacao: 'Selecione veia ázigos, hemiázigos e hemiázigos acessória para revisar o retorno venoso do tórax.',
    gatilhos: ['ázigos', 'azigos', 'hemiázigos', 'hemi-ázigos'],
    estruturasChave: ['veia ázigos', 'veia hemiázigos', 'veia hemiázigos acessória'],
    conteudo: ['Veia ázigos.', 'Veia hemiázigos.', 'Veia hemiázigos acessória.'],
    pontosResidencia: ['Serve como via colateral em obstruções da veia cava superior ou inferior.', 'É comum em interpretação de radiografias e tomografias.'],
  },
  {
    id: 'hilo-pulmonar',
    titulo: 'Hilo pulmonar',
    tipo: 'revisao-organica',
    sistema: 'respiratorio',
    regiao: 'torax',
    resumo: 'Revisão do encontro entre brônquio principal, artéria pulmonar e veias pulmonares no hilo.',
    visualizacao: 'Selecione pulmão ou brônquio principal e ative as relacionadas para comparar a disposição das estruturas hilares.',
    gatilhos: ['pulmão', 'pulmao', 'brônquio', 'bronquio', 'pulmonar', 'hilo pulmonar'],
    estruturasChave: ['pulmão do lado direito', 'pulmão do lado esquerdo', 'principal brônquio', 'artéria pulmonar', 'veia pulmonar superior', 'veia pulmonar inferior'],
    pontosResidencia: ['Regra mnemônica RALS: no hilo, a artéria pulmonar fica Anterior ao brônquio à direita e Superior ao brônquio à esquerda.', 'Veias pulmonares tendem a ocupar posição mais anterior e inferior.'],
    clinica: ['Importante em cirurgia torácica, radiologia e interpretação de TC.'],
  },
  {
    id: 'arvore-traqueobronquica',
    titulo: 'Árvore traqueobrônquica',
    tipo: 'revisao-organica',
    sistema: 'respiratorio',
    regiao: 'torax',
    resumo: 'Continuidade entre traqueia, brônquios principais e pulmões.',
    visualizacao: 'Selecione a traqueia e siga para os brônquios principais direito e esquerdo.',
    gatilhos: ['traqueia', 'brônquio', 'bronquio', 'árvore brônquica', 'arvore bronquica'],
    estruturasChave: ['traqueia', 'principal brônquio do lado direito', 'principal brônquio do lado esquerdo', 'pulmão do lado direito', 'pulmão do lado esquerdo'],
    conteudo: ['Traqueia.', 'Brônquios principais.', 'Pulmões.'],
    pontosResidencia: ['O brônquio principal direito é mais vertical, curto e calibroso.', 'Aspiração de corpo estranho tende a acometer mais o lado direito.'],
  },
  {
    id: 'diafragma-hiatos',
    titulo: 'Diafragma e hiatos',
    tipo: 'marco-clinico',
    sistema: 'muscular',
    regiao: 'torax',
    resumo: 'Músculo respiratório principal e marco entre tórax e abdome.',
    visualizacao: 'Selecione o diafragma e use esôfago, aorta e veia cava inferior como referências para os hiatos.',
    gatilhos: ['diafragma', 'hiato', 'esôfago', 'aorta', 'veia cava inferior'],
    estruturasChave: ['diafragma', 'esôfago', 'aorta', 'veia cava inferior'],
    conteudo: ['Hiato da veia cava inferior.', 'Hiato esofágico.', 'Hiato aórtico.'],
    pontosResidencia: ['I 8, 10 Eggs, At 12: VCI em T8, esôfago em T10, aorta em T12 é mnemônico clássico.', 'O diafragma tem relevância em hérnias hiatais e em trauma toracoabdominal.'],
    lacunasModelo: ['Os hiatos não surgem como recortes explicitamente nomeados; o estudo usa as estruturas que os atravessam como âncoras visuais.'],
  },
  {
    id: 'timo-mediastino-anterior',
    titulo: 'Timo e mediastino anterior',
    tipo: 'revisao-organica',
    sistema: 'endocrino',
    regiao: 'torax',
    resumo: 'Estrutura linfoepitelial importante em imunologia, imagem e síndromes do mediastino anterior.',
    visualizacao: 'Selecione os lobos do timo e observe suas relações centrais no tórax superior.',
    gatilhos: ['timo', 'mediastino anterior'],
    estruturasChave: ['lobo do timo', 'lobo do lado direito do timo', 'lobo do lado esquerdo do timo', 'veia cava superior'],
    conteudo: ['Lobos tímicos.', 'Relações mediastinais anteriores.'],
    pontosResidencia: ['Massas do mediastino anterior incluem timoma no diagnóstico diferencial.', 'O timo involui com a idade, mas permanece tema clássico em prova.'],
  },
  {
    id: 'triangulo-hesselbach',
    titulo: 'Triângulo de Hesselbach',
    tipo: 'marco-clinico',
    sistema: 'muscular',
    regiao: 'abdome',
    resumo: 'Marco clássico da parede abdominal anterior usado para diferenciar hérnias inguinais diretas das indiretas.',
    visualizacao: 'Use o modelo com foco na parede abdominal anterior e ative as estruturas relacionadas para visualizar os vasos epigástricos inferiores e o contexto inguinal.',
    gatilhos: ['hesselbach', 'hasselbach', 'epigástrica inferior', 'parede abdominal', 'abdome', 'inguinal'],
    estruturasChave: ['artéria epigástrica inferior', 'veia epigástrica inferior', 'parede abdominal anterior', 'abdome'],
    limites: ['Medial: borda lateral do músculo reto do abdome.', 'Lateral: vasos epigástricos inferiores.', 'Inferior: ligamento inguinal.'],
    conteudo: ['Área de fraqueza da parede abdominal posterior na região inguinal.', 'Relaciona-se ao trajeto do canal inguinal.'],
    pontosResidencia: ['Hérnia inguinal direta protrui medialmente aos vasos epigástricos inferiores.', 'Hérnia inguinal indireta acompanha o canal inguinal e fica lateral aos vasos epigástricos inferiores.'],
    clinica: ['Questões costumam pedir limites e a relação com hérnias da parede abdominal.'],
    lacunasModelo: ['O ligamento inguinal e o reto do abdome nem sempre aparecem como malhas isoladas nesta base; por isso o atlas destaca o contexto adjacente.'],
  },
  {
    id: 'canal-inguinal-cordao-espermatico',
    titulo: 'Canal inguinal e cordão espermático',
    tipo: 'marco-clinico',
    sistema: 'reprodutor',
    regiao: 'abdome',
    resumo: 'Tema recorrente em cirurgia e urologia, especialmente em hérnias e criptorquidia.',
    visualizacao: 'Selecione ducto deferente e testículo para usar o trajeto espermático como referência do canal inguinal.',
    gatilhos: ['canal inguinal', 'inguinal', 'cordão espermático', 'cordao espermatico', 'ducto deferente'],
    estruturasChave: ['ducto deferente', 'testículo', 'epidídimo', 'artéria epigástrica inferior'],
    conteudo: ['Anel profundo e superficial do canal.', 'Conteúdo espermático masculino.'],
    pontosResidencia: ['Hérnia indireta atravessa o anel inguinal profundo.', 'No homem, o cordão espermático percorre o canal inguinal.'],
    lacunasModelo: ['O canal e suas fáscias não estão segmentados como estruturas independentes; o atlas usa o ducto deferente e a topografia inguinal como apoio visual.'],
  },
  {
    id: 'triangulo-calot',
    titulo: 'Triângulo de Calot',
    tipo: 'correlacao-cirurgica',
    sistema: 'digestivo',
    regiao: 'abdome',
    resumo: 'Espaço cirúrgico da colecistectomia. A identificação segura de seus limites reduz lesão de via biliar.',
    visualizacao: 'Selecione vesícula biliar e mostre as estruturas relacionadas para estudar o encontro entre ducto cístico, ducto hepático comum e face inferior do fígado.',
    gatilhos: ['calot', 'ducto cístico', 'vesícula biliar', 'ducto hepático comum', 'vias biliares'],
    estruturasChave: ['vesícula biliar', 'ducto cístico', 'ducto hepático comum', 'fígado'],
    limites: ['Lateral: ducto cístico.', 'Medial: ducto hepático comum.', 'Superior: face inferior do fígado.'],
    conteudo: ['Tradicionalmente a artéria cística cruza a área, embora sua anatomia seja variável.'],
    pontosResidencia: ['O "critical view of safety" é tema recorrente em cirurgia geral.', 'Lesão de via biliar é risco central quando a anatomia está distorcida por inflamação.'],
    clinica: ['Colecistite e cirurgia biliar aparecem com frequência em provas e discussões de internato cirúrgico.'],
    lacunasModelo: ['A artéria cística não está isolada de forma consistente nesta base; o estudo visual se apoia nos ductos e na vesícula.'],
  },
  {
    id: 'vias-biliares-extra-hepaticas',
    titulo: 'Vias biliares extra-hepáticas',
    tipo: 'revisao-organica',
    sistema: 'digestivo',
    regiao: 'abdome',
    resumo: 'Panorama do escoamento biliar útil para integrar fígado, vesícula e ductos.',
    visualizacao: 'Selecione a vesícula biliar ou o ducto biliar e ative as relacionadas para revisar a continuidade entre ductos hepáticos, ducto cístico e ducto biliar.',
    gatilhos: ['biliar', 'vesícula', 'ducto hepático comum', 'ducto cístico', 'colédoco', 'ducto bile'],
    estruturasChave: ['vesícula biliar', 'ducto cístico', 'ducto hepático comum', 'ducto bile', 'ducto bile extra-hepático'],
    pontosResidencia: ['A união entre ducto cístico e ducto hepático comum forma o ducto biliar principal.', 'Icterícia obstrutiva e colangite aparecem com frequência em casos clínicos.'],
    clinica: ['Relevante para cirurgia geral, gastroenterologia e radiologia abdominal.'],
  },
  {
    id: 'triade-portal',
    titulo: 'Tríade portal e pedículo hepático',
    tipo: 'revisao-organica',
    sistema: 'digestivo',
    regiao: 'abdome',
    resumo: 'Conjunto clássico do ligamento hepatoduodenal, fundamental para estudo do hilo hepático.',
    visualizacao: 'Com fígado selecionado, use as estruturas relacionadas para observar veia porta e ducto biliar extra-hepático no pedículo hepático.',
    gatilhos: ['porta', 'fígado', 'ducto biliar', 'pedículo hepático', 'tríade portal'],
    estruturasChave: ['fígado', 'veia porta hepática', 'veia porta', 'ducto bile extra-hepático', 'ducto hepático comum'],
    conteudo: ['Veia porta hepática.', 'Via biliar principal.', 'Artéria hepática própria como terceiro elemento clássico.'],
    pontosResidencia: ['Manobra de Pringle comprime temporariamente o pedículo hepático para controle de sangramento.', 'A veia porta costuma ocupar posição posterior no conjunto.'],
    clinica: ['Importante em trauma hepático, cirurgia hepatobiliar e hipertensão portal.'],
    lacunasModelo: ['A artéria hepática própria pode não estar destacada de forma isolada no modelo; o atlas registra isso explicitamente.'],
  },
  {
    id: 'tronco-celiaco',
    titulo: 'Tronco celíaco',
    tipo: 'marco-clinico',
    sistema: 'arterial',
    regiao: 'abdome',
    resumo: 'Primeira grande ramificação visceral da aorta abdominal, central para irrigação do intestino anterior.',
    visualizacao: 'Selecione a artéria celíaca e a aorta abdominal para revisar a origem do tronco celíaco.',
    gatilhos: ['celíaco', 'celiaco', 'tronco celíaco', 'tronco celiaco', 'aorta abdominal'],
    estruturasChave: ['celíaco tronco', 'artéria celíaco', 'aorta abdominal', 'fígado', 'estômago', 'baço'],
    conteudo: ['Origem na aorta abdominal.', 'Irrigação do intestino anterior.'],
    pontosResidencia: ['Os ramos clássicos são gástrica esquerda, esplênica e hepática comum.', 'Questões frequentemente cobram território vascular e correlação com órgãos derivados do intestino anterior.'],
    lacunasModelo: ['Nem todos os ramos clássicos estão segmentados nominalmente; use o tronco e os órgãos-alvo como referência.'],
  },
  {
    id: 'arteria-mesenterica-superior',
    titulo: 'Artéria mesentérica superior',
    tipo: 'marco-clinico',
    sistema: 'arterial',
    regiao: 'abdome',
    resumo: 'Vaso-chave do intestino médio, muito cobrado em cirurgia e radiologia.',
    visualizacao: 'Selecione a artéria mesentérica superior com jejuno, íleo, ceco e cólon para associar território vascular.',
    gatilhos: ['mesentérica superior', 'mesenterica superior', 'ams'],
    estruturasChave: ['artéria mesentérica superior', 'jejuno', 'íleo', 'ceco', 'apêndice vermiforme'],
    conteudo: ['Território do intestino médio.', 'Relação com delgado e ceco.'],
    pontosResidencia: ['Irriga do duodeno distal até dois terços proximais do transverso.', 'É tema clássico em isquemia mesentérica aguda.'],
  },
  {
    id: 'arteria-mesenterica-inferior',
    titulo: 'Artéria mesentérica inferior',
    tipo: 'marco-clinico',
    sistema: 'arterial',
    regiao: 'abdome',
    resumo: 'Vaso do intestino posterior, frequente em provas de irrigação do cólon.',
    visualizacao: 'Selecione a artéria mesentérica inferior com descendente cólon, sigmoide e reto.',
    gatilhos: ['mesentérica inferior', 'mesenterica inferior', 'ami'],
    estruturasChave: ['artéria mesentérica inferior', 'descendente cólon', 'sigmoide cólon', 'reto'],
    conteudo: ['Território do intestino posterior.'],
    pontosResidencia: ['Irriga do terço distal do transverso até parte superior do reto.', 'Importante em isquemia do cólon e em cirurgia colorretal.'],
  },
  {
    id: 'estomago-baco',
    titulo: 'Estômago e baço',
    tipo: 'revisao-organica',
    sistema: 'digestivo',
    regiao: 'abdome',
    resumo: 'Revisão topográfica do quadrante superior esquerdo.',
    visualizacao: 'Selecione estômago e baço para revisar vizinhança e compartimento abdominal superior.',
    gatilhos: ['estômago', 'estomago', 'baço', 'quadrante superior esquerdo'],
    estruturasChave: ['estômago', 'baço', 'diafragma', 'pâncreas'],
    conteudo: ['Estômago.', 'Baço.', 'Relação com diafragma e pâncreas.'],
    pontosResidencia: ['Traumas esplênicos e úlceras gástricas costumam exigir boa noção topográfica.', 'O baço é intraperitoneal e altamente vascularizado.'],
  },
  {
    id: 'pancreas-duodeno',
    titulo: 'Pâncreas e duodeno',
    tipo: 'revisao-organica',
    sistema: 'digestivo',
    regiao: 'abdome',
    resumo: 'Integração anatômica frequente em provas de clínica, cirurgia e imagem abdominal.',
    visualizacao: 'Selecione pâncreas e duodeno para visualizar a unidade pancreatoduodenal.',
    gatilhos: ['pâncreas', 'pancreas', 'duodeno'],
    estruturasChave: ['pâncreas', 'parênquima do pâncreas', 'duodeno', 'ducto bile extra-hepático'],
    conteudo: ['Pâncreas.', 'Duodeno.', 'Relação com via biliar distal.'],
    pontosResidencia: ['Cabeça do pâncreas relaciona-se intimamente ao duodeno.', 'Tumores periampulares e pancreatite aparecem recorrentemente.'],
  },
  {
    id: 'intestino-delgado',
    titulo: 'Jejuno e íleo',
    tipo: 'revisao-organica',
    sistema: 'digestivo',
    regiao: 'abdome',
    resumo: 'Revisão macroscópica do intestino delgado e de seus segmentos principais.',
    visualizacao: 'Selecione jejuno e íleo para comparar seus segmentos e sua distribuição no abdome.',
    gatilhos: ['jejuno', 'íleo', 'ileo', 'delgado'],
    estruturasChave: ['zona do jejuno', 'zona do íleo', 'parte proximal do jejuno', 'parte proximal do íleo'],
    conteudo: ['Jejuno.', 'Íleo.'],
    pontosResidencia: ['Jejuno tende a ter pregas mais proeminentes e paredes mais espessas.', 'Íleo apresenta mais tecido linfoide associado.'],
  },
  {
    id: 'colon-ceco-apendice',
    titulo: 'Cólon, ceco e apêndice',
    tipo: 'marco-clinico',
    sistema: 'digestivo',
    regiao: 'abdome',
    resumo: 'Conjunto fundamental para clínica abdominal aguda e cirurgia geral.',
    visualizacao: 'Selecione ceco, apêndice vermiforme e segmentos do cólon para revisar continuidade e topografia.',
    gatilhos: ['cólon', 'colon', 'ceco', 'apêndice', 'apendice', 'fossa ilíaca direita'],
    estruturasChave: ['ceco', 'apêndice vermiforme', 'ascendente cólon', 'transverso cólon', 'descendente cólon', 'sigmoide cólon'],
    conteudo: ['Ceco.', 'Apêndice vermiforme.', 'Segmentos do cólon.'],
    pontosResidencia: ['Apendicite aguda é um dos temas mais recorrentes de abdome agudo.', 'O ponto de McBurney é marco de superfície frequentemente citado.'],
    lacunasModelo: ['O ponto de McBurney é referência de superfície, não uma malha anatômica isolada no atlas.'],
  },
  {
    id: 'aorta-abdominal-vci',
    titulo: 'Aorta abdominal e veia cava inferior',
    tipo: 'revisao-organica',
    sistema: 'arterial',
    regiao: 'abdome',
    resumo: 'Eixo vascular central do retroperitônio.',
    visualizacao: 'Selecione aorta abdominal e veia cava inferior para estudar o corredor vascular abdominal.',
    gatilhos: ['aorta abdominal', 'veia cava inferior', 'retroperitônio', 'retroperitonio'],
    estruturasChave: ['aorta abdominal', 'veia cava inferior', 'artéria renal', 'veia renal'],
    conteudo: ['Aorta abdominal.', 'Veia cava inferior.', 'Relações com vasos renais.'],
    pontosResidencia: ['A bifurcação aórtica e o posicionamento da VCI são marcos fundamentais.', 'A relação com artérias renais e ilíacas é muito cobrada.'],
  },
  {
    id: 'pediculo-renal',
    titulo: 'Pedículo renal',
    tipo: 'revisao-organica',
    sistema: 'urinario',
    regiao: 'abdome',
    resumo: 'Relação entre artéria renal, veia renal e ureter no hilo do rim, útil em urologia e cirurgia.',
    visualizacao: 'Selecione o rim e ative as estruturas relacionadas para revisar artéria renal, veia renal e ureter.',
    gatilhos: ['rim', 'renal', 'ureter', 'pedículo renal', 'pediculo renal'],
    estruturasChave: ['rim', 'artéria renal', 'veia renal', 'ureter'],
    conteudo: ['Veia renal.', 'Artéria renal.', 'Pelve renal/ureter.'],
    pontosResidencia: ['Da frente para trás, a organização clássica é veia, artéria e pelve renal/ureter.', 'A veia renal esquerda costuma ter relações anatômicas mais exploradas em prova.'],
    clinica: ['Cobrado em trauma renal, nefrectomia e hidronefrose.'],
  },
  {
    id: 'retroperitonio-ureter',
    titulo: 'Retroperitônio e ureter',
    tipo: 'revisao-organica',
    sistema: 'urinario',
    regiao: 'abdome',
    resumo: 'Estruturação básica do trajeto ureteral no retroperitônio.',
    visualizacao: 'Selecione ureter, rim e vasos renais para seguir o trajeto do trato urinário superior.',
    gatilhos: ['retroperitônio', 'retroperitonio', 'ureter'],
    estruturasChave: ['ureter', 'rim', 'artéria renal', 'veia renal', 'aorta abdominal'],
    conteudo: ['Ureter.', 'Relações renais e retroperitoneais.'],
    pontosResidencia: ['Constrições ureterais são clássicas em nefrolitíase.', 'A topografia retroperitoneal ajuda na leitura de TC e na cirurgia.'],
  },
  {
    id: 'bexiga-prostata-uretra',
    titulo: 'Bexiga, próstata e uretra',
    tipo: 'revisao-organica',
    sistema: 'urinario',
    regiao: 'pelve',
    resumo: 'Bloco central da pelve masculina, muito útil em urologia.',
    visualizacao: 'Selecione bexiga urinária, próstata e uretra para revisar o trato urinário inferior masculino.',
    gatilhos: ['bexiga', 'próstata', 'prostata', 'uretra', 'pelve masculina'],
    estruturasChave: ['bexiga urinária', 'próstata', 'uretra'],
    conteudo: ['Bexiga urinária.', 'Próstata.', 'Uretra.'],
    pontosResidencia: ['A hiperplasia prostática benigna comprime a uretra prostática.', 'A relação entre bexiga e próstata é central em sintomas urinários baixos.'],
  },
  {
    id: 'testiculo-epididimo-deferente',
    titulo: 'Testículo, epidídimo e ducto deferente',
    tipo: 'revisao-organica',
    sistema: 'reprodutor',
    regiao: 'pelve',
    resumo: 'Unidade anatômica básica do sistema reprodutor masculino.',
    visualizacao: 'Selecione testículo, epidídimo e ducto deferente para seguir a via espermática.',
    gatilhos: ['testículo', 'testiculo', 'epidídimo', 'epididimo', 'ducto deferente'],
    estruturasChave: ['testículo', 'epidídimo', 'ducto deferente'],
    conteudo: ['Testículo.', 'Epidídimo.', 'Ducto deferente.'],
    pontosResidencia: ['O epidídimo participa da maturação e armazenamento de espermatozoides.', 'O ducto deferente conduz os espermatozoides em direção à pelve.'],
  },
  {
    id: 'vesicula-seminal-trato-reprodutor',
    titulo: 'Vesícula seminal e trato reprodutor masculino',
    tipo: 'revisao-organica',
    sistema: 'reprodutor',
    regiao: 'pelve',
    resumo: 'Complementa a via espermática e integra os órgãos acessórios masculinos.',
    visualizacao: 'Selecione vesícula seminal, ducto deferente e próstata para revisar a via ejaculatória.',
    gatilhos: ['vesícula seminal', 'vesicula seminal', 'trato reprodutor', 'ejaculatório'],
    estruturasChave: ['vesícula seminal', 'ducto deferente', 'próstata'],
    conteudo: ['Vesículas seminais.', 'Ductos deferentes.', 'Próstata.'],
    pontosResidencia: ['A secreção das vesículas seminais compõe grande parte do volume seminal.', 'Tema frequente em infertilidade, próstata e anatomia pélvica masculina.'],
  },
  {
    id: 'penis-corpos-eretis',
    titulo: 'Pênis: corpos eréteis',
    tipo: 'revisao-organica',
    sistema: 'reprodutor',
    regiao: 'pelve',
    resumo: 'Revisão macroscópica dos componentes eréteis externos.',
    visualizacao: 'Selecione glande, corpo esponjoso e corpos cavernosos para estudar a organização do pênis.',
    gatilhos: ['pênis', 'penis', 'glande', 'corpo esponjoso', 'corpo cavernoso'],
    estruturasChave: ['glande do pênis', 'corpo esponjoso do pênis', 'corpo cavernoso do pênis'],
    conteudo: ['Glande.', 'Corpo esponjoso.', 'Corpos cavernosos.'],
    pontosResidencia: ['O corpo esponjoso envolve a uretra esponjosa.', 'Corpos cavernosos são os principais responsáveis pela rigidez erétil.'],
  },
  {
    id: 'vasos-iliacos-pelve',
    titulo: 'Vasos ilíacos e pelve',
    tipo: 'revisao-organica',
    sistema: 'arterial',
    regiao: 'pelve',
    resumo: 'Conexão entre circulação abdominal e membros inferiores/pelve.',
    visualizacao: 'Selecione artérias e veias ilíacas comuns para revisar a transição vascular ao nível pélvico.',
    gatilhos: ['ilíaca', 'iliaca', 'pelve', 'vasos ilíacos'],
    estruturasChave: ['artéria ilíaca comum', 'veia ilíaca comum', 'aorta abdominal', 'veia cava inferior'],
    conteudo: ['Artérias ilíacas comuns.', 'Veias ilíacas comuns.'],
    pontosResidencia: ['A bifurcação da aorta em ilíacas comuns é marco obrigatório.', 'Trombose e doença aterosclerótica usam esse território como base anatômica.'],
  },
  {
    id: 'assoalho-pelvico-masculino',
    titulo: 'Assoalho pélvico masculino',
    tipo: 'revisao-organica',
    sistema: 'muscular',
    regiao: 'pelve',
    resumo: 'Base do suporte visceral pélvico e do controle esfincteriano.',
    visualizacao: 'Selecione a zona do levantador do ânus e relacione com reto, próstata e bexiga.',
    gatilhos: ['assoalho pélvico', 'assoalho pelvico', 'levantador do ânus', 'levator ani'],
    estruturasChave: ['zona do levantador do ânus', 'arco tendíneo do levantador do ânus', 'reto', 'próstata', 'bexiga urinária'],
    conteudo: ['Levantador do ânus.', 'Suporte pélvico visceral.'],
    pontosResidencia: ['O assoalho pélvico é importante para continência.', 'Lesões musculares e disfunções pélvicas exigem boa noção anatômica.'],
    lacunasModelo: ['O complexo muscular do assoalho pélvico aparece parcialmente segmentado; o atlas usa as zonas nomeadas disponíveis.'],
  },
  {
    id: 'cintura-escapular-manguito-rotador',
    titulo: 'Cintura escapular e manguito rotador',
    tipo: 'revisao-organica',
    sistema: 'muscular',
    regiao: 'membro-superior',
    resumo: 'Bloco essencial de ortopedia e exame do ombro.',
    visualizacao: 'Selecione escápula, clavícula, úmero e músculos supraespinal, infraespinal, subescapular e redondo menor.',
    gatilhos: ['manguito rotador', 'ombro', 'escápula', 'escapula', 'úmero', 'umero'],
    estruturasChave: ['escápula', 'clavícula', 'úmero', 'supraespinal', 'infraespinal', 'subescapular', 'redondo menor'],
    conteudo: ['Arcabouço ósseo do ombro.', 'Músculos do manguito rotador.'],
    pontosResidencia: ['SITS: supraespinal, infraespinal, redondo menor e subescapular.', 'Lesões do manguito, especialmente do supraespinal, são muito cobradas.'],
  },
  {
    id: 'axila-transicao-subclavio-axilar',
    titulo: 'Axila e transição subclávio-axilar',
    tipo: 'revisao-organica',
    sistema: 'arterial',
    regiao: 'membro-superior',
    resumo: 'Zona anatômica importante em trauma, acesso vascular e linfonodos.',
    visualizacao: 'Selecione artéria subclávia, veia axilar e estruturas do ombro para revisar a transição cervicotorácica para o membro superior.',
    gatilhos: ['axila', 'axilar', 'subclávia', 'subclavia'],
    estruturasChave: ['artéria subclávio', 'veia axilar', 'clavícula', 'escápula'],
    conteudo: ['Transição subclávio-axilar.', 'Relações com a cintura escapular.'],
    pontosResidencia: ['A axila é via importante para avaliação de linfonodos e abordagem de vasos.', 'A continuidade subclávia-axilar é tema clássico em anatomia aplicada.'],
    lacunasModelo: ['O plexo braquial nem sempre está isolado como malha dedicada; o estudo é mais vascular e osteomuscular.'],
  },
  {
    id: 'fossa-cubital',
    titulo: 'Fossa cubital',
    tipo: 'marco-clinico',
    sistema: 'arterial',
    regiao: 'membro-superior',
    resumo: 'Marco clássico para punções, gasometria e avaliação vascular do membro superior.',
    visualizacao: 'Selecione artéria braquial, artéria radial, artéria ulnar e veia cubital mediana para estudar o cotovelo anterior.',
    gatilhos: ['fossa cubital', 'cotovelo anterior', 'braquial', 'cubital'],
    estruturasChave: ['artéria braquial', 'artéria radial', 'artéria ulnar', 'veia cubital mediano'],
    conteudo: ['Bifurcação braquial.', 'Rede venosa superficial.'],
    pontosResidencia: ['A veia cubital mediana é local frequente de punção venosa.', 'A artéria braquial se divide em radial e ulnar na região do cotovelo.'],
    lacunasModelo: ['O tendão do bíceps braquial e o nervo mediano não aparecem sempre como elementos isolados no atlas.'],
  },
  {
    id: 'tunel-carpo',
    titulo: 'Túnel do carpo',
    tipo: 'marco-clinico',
    sistema: 'conjuntivo',
    regiao: 'membro-superior',
    resumo: 'Canal osteofibroso do punho, essencial na síndrome compressiva mais cobrada da mão.',
    visualizacao: 'Selecione o punho ou o retináculo dos flexores e ative as relacionadas para revisar os ossos do carpo que formam o assoalho e as paredes do túnel.',
    gatilhos: ['carpo', 'punho', 'retináculo', 'retinaculo', 'túnel do carpo', 'tunel do carpo'],
    estruturasChave: ['flexor retináculo do punho', 'osso do carpo', 'metacarpo'],
    limites: ['Teto: retináculo dos flexores.', 'Assoalho e paredes: arco côncavo dos ossos do carpo.'],
    conteudo: ['Nervo mediano.', 'Tendões flexores dos dedos e do polegar.'],
    pontosResidencia: ['Parestesia em polegar, indicador, médio e metade radial do anular sugere compressão do nervo mediano.', 'A eminência tenar pode atrofiar nos casos crônicos.'],
    clinica: ['Muito frequente em ortopedia, neurologia e medicina de família.'],
    lacunasModelo: ['O nervo mediano não aparece como malha isolada estável nesta base; o foco visual recai sobre o arcabouço osteofibroso.'],
  },
  {
    id: 'tabaqueira-anatomica',
    titulo: 'Tabaqueira anatômica',
    tipo: 'marco-clinico',
    sistema: 'arterial',
    regiao: 'membro-superior',
    resumo: 'Depressão lateral do punho, importante para semiologia e fraturas do escafoide.',
    visualizacao: 'Use a artéria radial, o punho e o primeiro metacarpo como referência para o estudo da tabaqueira anatômica.',
    gatilhos: ['tabaqueira anatômica', 'tabaqueira anatomica', 'artéria radial', 'punho'],
    estruturasChave: ['artéria radial', 'metacarpo 1º', 'osso do carpo'],
    conteudo: ['Artéria radial.', 'Base óssea do carpo e do polegar.'],
    pontosResidencia: ['Dor na tabaqueira anatômica sugere fratura de escafoide.', 'A artéria radial pode ser palpada na região.'],
    lacunasModelo: ['Tendões que delimitam a tabaqueira não estão todos destacados como malhas independentes.'],
  },
  {
    id: 'compartimento-flexor-antebraco',
    titulo: 'Compartimento flexor do antebraço',
    tipo: 'revisao-organica',
    sistema: 'muscular',
    regiao: 'membro-superior',
    resumo: 'Revisão muscular e funcional importante para provas de ortopedia e neurologia periférica.',
    visualizacao: 'Selecione flexor do carpo radial, flexor do carpo ulnar, palmar longo e pronador redondo.',
    gatilhos: ['antebraço', 'antebraco', 'flexor do carpo', 'palmar longo', 'pronador redondo'],
    estruturasChave: ['flexor do carpo radial', 'cabeça umeral do flexor do carpo ulnar', 'cabeça ulnar do flexor do carpo ulnar', 'palmar longo', 'cabeça umeral do pronador redondo'],
    conteudo: ['Flexores superficiais do antebraço.', 'Pronador redondo.'],
    pontosResidencia: ['O pronador redondo cruza anteriormente a região proximal do antebraço.', 'Os flexores do carpo participam da flexão e desvio radial/ulnar do punho.'],
  },
  {
    id: 'triangulo-femoral',
    titulo: 'Triângulo femoral',
    tipo: 'marco-clinico',
    sistema: 'arterial',
    regiao: 'membro-inferior',
    resumo: 'Janela anatômica de palpação arterial, punção vascular e correlação com hérnias femorais.',
    visualizacao: 'Com a coxa proximal em foco, ative artéria femoral, veia femoral, sartório e adutor longo para visualizar os limites mais cobrados.',
    gatilhos: ['femoral', 'coxa', 'sartório', 'adutor longo', 'triângulo femoral'],
    estruturasChave: ['artéria femoral', 'veia femoral', 'sartório', 'adutor longo'],
    limites: ['Superior: ligamento inguinal.', 'Lateral: borda medial do sartório.', 'Medial: borda medial do adutor longo.'],
    conteudo: ['Nervo femoral, artéria femoral, veia femoral e canal femoral.'],
    pontosResidencia: ['A ordem lateral → medial é NAVL: nervo, artéria, veia, linfáticos.', 'Palpação do pulso femoral e acesso arterial são aplicações práticas recorrentes.'],
    clinica: ['Questões de acesso vascular e de hérnia femoral usam esse marco.'],
    lacunasModelo: ['O ligamento inguinal e o nervo femoral podem não estar isolados no conjunto geométrico atual.'],
  },
  {
    id: 'regiao-glutea-quadrantes',
    titulo: 'Região glútea e quadrantes seguros',
    tipo: 'marco-clinico',
    sistema: 'muscular',
    regiao: 'membro-inferior',
    resumo: 'Tema essencial para injeções intramusculares e para a anatomia do quadril.',
    visualizacao: 'Selecione glúteo médio e estruturas do quadril para revisar a região glútea.',
    gatilhos: ['glútea', 'glutea', 'quadrante glúteo', 'glúteo médio', 'gluteo medio'],
    estruturasChave: ['glúteo médio', 'fêmur', 'pelve'],
    conteudo: ['Região glútea.', 'Quadrante superolateral seguro para injeção.'],
    pontosResidencia: ['A aplicação intramuscular prefere o quadrante superolateral para reduzir risco neurovascular.', 'A região glútea é frequentemente abordada em trauma e ortopedia.'],
    lacunasModelo: ['O nervo ciático não está segmentado de forma consistente nesta base.'],
  },
  {
    id: 'fossa-poplitea',
    titulo: 'Fossa poplítea',
    tipo: 'marco-clinico',
    sistema: 'arterial',
    regiao: 'membro-inferior',
    resumo: 'Espaço anatômico posterior do joelho com grande relevância vascular.',
    visualizacao: 'Selecione artéria poplítea e veia poplítea para revisar o joelho posterior.',
    gatilhos: ['fossa poplítea', 'fossa poplitea', 'poplítea', 'poplitea'],
    estruturasChave: ['artéria poplítea', 'veia poplítea', 'fêmur', 'tíbia'],
    conteudo: ['Artéria poplítea.', 'Veia poplítea.'],
    pontosResidencia: ['A artéria poplítea é continuação da femoral após o hiato do adutor.', 'Cistos poplíteos e aneurismas da poplítea são correlações clássicas.'],
    lacunasModelo: ['Os nervos tibial e fibular comum não aparecem de forma estável como malhas isoladas.'],
  },
  {
    id: 'compartimento-anterior-perna',
    titulo: 'Compartimento anterior da perna',
    tipo: 'revisao-organica',
    sistema: 'muscular',
    regiao: 'membro-inferior',
    resumo: 'Revisão do compartimento extensor/dorsiflexor da perna.',
    visualizacao: 'Selecione tibial anterior, artéria tibial anterior e ossos da perna.',
    gatilhos: ['tibial anterior', 'compartimento anterior da perna', 'dorsiflexão'],
    estruturasChave: ['tibial anterior', 'artéria tibial anterior', 'tíbia', 'fíbula'],
    conteudo: ['Músculo tibial anterior.', 'Artéria tibial anterior.'],
    pontosResidencia: ['O tibial anterior é importante na dorsiflexão do pé.', 'Síndrome compartimental anterior é correlação frequente.'],
  },
  {
    id: 'tendao-calcaneo-retrope',
    titulo: 'Tendão calcâneo e retropé',
    tipo: 'marco-clinico',
    sistema: 'muscular',
    regiao: 'membro-inferior',
    resumo: 'Marco anatômico de alta frequência em ortopedia e medicina esportiva.',
    visualizacao: 'Selecione tendão calcâneo, calcâneo e estruturas posteriores da perna.',
    gatilhos: ['tendão calcâneo', 'tendao calcaneo', 'aquiles', 'calcâneo', 'calcaneo'],
    estruturasChave: ['tendão calcâneo', 'calcâneo', 'tibial anterior'],
    conteudo: ['Tendão calcâneo.', 'Inserção no calcâneo.'],
    pontosResidencia: ['Ruptura do tendão de Aquiles é tema clássico.', 'O reflexo aquileu avalia principalmente S1.'],
  },
  {
    id: 'joelho-mecanismo-extensor',
    titulo: 'Joelho: mecanismo extensor',
    tipo: 'revisao-organica',
    sistema: 'muscular',
    regiao: 'membro-inferior',
    resumo: 'Integra quadríceps, patela e tíbia na extensão do joelho.',
    visualizacao: 'Selecione reto femoral, patela, tíbia e fêmur para revisar o aparelho extensor.',
    gatilhos: ['joelho', 'patela', 'quadríceps', 'quadriceps', 'reto femoral'],
    estruturasChave: ['reto femoral', 'patela', 'tíbia', 'fêmur'],
    conteudo: ['Quadríceps.', 'Patela.', 'Inserção tibial.'],
    pontosResidencia: ['A patela aumenta o braço de alavanca do quadríceps.', 'Luxação patelar e lesões extensoras exigem entendimento desse conjunto.'],
    lacunasModelo: ['Ligamentos cruzados e patelar não estão detalhados como malhas independentes neste conjunto.'],
  },
  {
    id: 'tarso-arcos-pe',
    titulo: 'Tarso e arcos do pé',
    tipo: 'revisao-organica',
    sistema: 'esqueletico',
    regiao: 'membro-inferior',
    resumo: 'Base para revisão de apoio plantar e anatomia do pé.',
    visualizacao: 'Selecione ossos do tarso, metatarso e calcâneo para revisar o esqueleto do pé.',
    gatilhos: ['tarso', 'pé', 'pe', 'metatarso', 'calcâneo', 'calcaneo'],
    estruturasChave: ['osso do tarso', 'metatarso', 'calcâneo'],
    conteudo: ['Tarso.', 'Metatarso.', 'Calcâneo.'],
    pontosResidencia: ['O calcâneo é o principal osso de apoio posterior.', 'Arcos plantares aparecem em temas de ortopedia e biomecânica.'],
    lacunasModelo: ['Os arcos do pé são conceitos funcionais; o atlas os demonstra por meio das peças ósseas que os compõem.'],
  },
  {
    id: 'coluna-vertebral',
    titulo: 'Coluna vertebral',
    tipo: 'revisao-organica',
    sistema: 'esqueletico',
    regiao: 'coluna-dorso',
    resumo: 'Panorama ósseo da sustentação axial e das curvaturas da coluna.',
    visualizacao: 'Selecione vértebras e navegue por segmentos cervical, torácico, lombar, sacro e cóccix.',
    gatilhos: ['coluna', 'vértebra', 'vertebra', 'sacro', 'cóccix', 'coccix'],
    estruturasChave: ['vértebra cervical', 'vértebra torácica', 'vértebra lombar', 'sacro', 'cóccix'],
    conteudo: ['Segmentos cervical, torácico e lombar.', 'Sacro.', 'Cóccix.'],
    pontosResidencia: ['As curvaturas fisiológicas são tema básico e recorrente.', 'Fraturas vertebrais e hérnias discais exigem boa noção segmentar.'],
    lacunasModelo: ['Os discos intervertebrais e ligamentos da coluna não estão todos isolados como peças nomeadas.'],
  },
  {
    id: 'sacro-pelve-ossea',
    titulo: 'Sacro e pelve óssea',
    tipo: 'revisao-organica',
    sistema: 'esqueletico',
    regiao: 'pelve',
    resumo: 'Integra a cintura pélvica ao esqueleto axial.',
    visualizacao: 'Selecione sacro, pelve e fêmur proximal para revisar a base óssea pélvica.',
    gatilhos: ['sacro', 'pelve óssea', 'pelve ossea'],
    estruturasChave: ['sacro', 'pelve', 'fêmur'],
    conteudo: ['Sacro.', 'Anel pélvico.', 'Conexão com o fêmur.'],
    pontosResidencia: ['Fraturas pélvicas e avaliação obstétrica/anatômica começam pelo entendimento do anel pélvico.', 'O sacro conecta coluna e pelve.'],
    lacunasModelo: ['Alguns detalhes das linhas e forames sacrais não aparecem como malhas separadas.'],
  },
];


export function resolverFichasEstudoDetalhado(indice: ConceitoIndexado[]): FichaEstudoResolvida[] {
  return FICHAS_ESTUDO_DETALHADO.map((ficha) => ({
    ...ficha,
    conceitosRelacionados: localizarConceitos(indice, [
      ...ficha.estruturasChave,
      ...ficha.gatilhos,
    ]).slice(0, 16),
  }));
}

function pontuarRelacionamento(ficha: FichaEstudoResolvida, item: ConceitoIndexado): number {
  const texto = chaveBusca(item);
  let pontos = 0;

  if (ficha.sistema && ficha.sistema === item.sistema) pontos += 3;
  if (ficha.regiao && ficha.regiao === item.regiao) pontos += 2;
  if (ficha.conceitosRelacionados.some((rel) => rel.conceito.id === item.conceito.id)) pontos += 10;

  ficha.gatilhos.forEach((gatilho) => {
    if (texto.includes(normalizar(gatilho))) pontos += 4;
  });
  ficha.estruturasChave.forEach((termo) => {
    if (texto.includes(normalizar(termo))) pontos += 5;
  });

  return pontos;
}

export function fichasRelacionadasAoConceito(
  fichas: FichaEstudoResolvida[],
  item: ConceitoIndexado,
  limite = 5,
): FichaEstudoResolvida[] {
  return fichas
    .map((ficha) => ({ficha, pontos: pontuarRelacionamento(ficha, item)}))
    .filter(({pontos}) => pontos >= 5)
    .sort((a, b) => b.pontos - a.pontos || a.ficha.titulo.localeCompare(b.ficha.titulo, 'pt-BR'))
    .slice(0, limite)
    .map(({ficha}) => ficha);
}
