import type {ConceitoIndexado} from './catalogo-anatomico.ts';

export type AreaEstudoAvancado = 'neuroanatomia' | 'arterial' | 'venoso' | 'linfatico' | 'nervos-perifericos' | 'especialidades';

export interface EtapaRotaEstudo { titulo: string; termos: string[]; explicacao: string; }

export interface RotaEstudoAvancado { id: string; titulo: string; area: AreaEstudoAvancado; resumo: string; etapas: EtapaRotaEstudo[]; pontosResidencia: string[]; lacunasModelo: string[]; especialidade?: string; }

export interface EtapaRotaResolvida extends EtapaRotaEstudo { conceitos: ConceitoIndexado[]; }

export interface RotaEstudoResolvida extends Omit<RotaEstudoAvancado, 'etapas'> { etapas: EtapaRotaResolvida[]; totalConceitos: number; }

export const NOMES_AREA_ESTUDO: Record<AreaEstudoAvancado, string> = { 'neuroanatomia':'Neuroanatomia fina', 'arterial':'Vascular arterial', 'venoso':'Vascular venosa', 'linfatico':'Linfáticos', 'nervos-perifericos':'Nervos periféricos', 'especialidades':'Por especialidade' };

function normalizar(texto: string): string { return texto.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim(); }

function chave(item: ConceitoIndexado): string { return normalizar([item.conceito.nome,item.conceito.nomeOriginal,item.conceito.id,...item.aliases].filter(Boolean).join(' ')); }

function localizar(indice: ConceitoIndexado[], termos: string[]): ConceitoIndexado[] { const mapa=new Map<string,ConceitoIndexado>(); for (const termoBruto of termos){ const termo=normalizar(termoBruto); if(!termo) continue; indice.filter(item=>chave(item).includes(termo)).slice(0,6).forEach(item=>mapa.set(item.conceito.id,item)); } return [...mapa.values()].slice(0,8); }

export const ROTAS_ESTUDO_AVANCADO: RotaEstudoAvancado[] = [
  {
    id: 'neuro-circulo-willis',
    titulo: 'Círculo de Willis',
    area: 'neuroanatomia',
    resumo: 'Percurso arterial da base do encéfalo e suas comunicações.',
    etapas: [
      {titulo:'Carótida interna', termos:['artéria carótida interna'], explicacao:'Entrada anterior da circulação cerebral.'},
      {titulo:'Cerebral anterior e comunicante anterior', termos:['artéria cerebral anterior', 'artéria comunicante anterior'], explicacao:'Componente anterior do círculo.'},
      {titulo:'Comunicantes posteriores', termos:['artéria comunicante posterior'], explicacao:'Conexão entre circulação carotídea e posterior.'},
      {titulo:'Cerebral posterior', termos:['artéria cerebral posterior'], explicacao:'Componente posterior do círculo.'},
    ],
    pontosResidencia: ['Aneurismas saculares são cobrados nas bifurcações e comunicações.', 'Integre território vascular com déficits neurológicos.'],
    lacunasModelo: [],
  },
  {
    id: 'neuro-capsula-interna',
    titulo: 'Cápsula interna e núcleos da base',
    area: 'neuroanatomia',
    resumo: 'Rota para correlacionar fibras de projeção com estruturas profundas do telencéfalo.',
    etapas: [
      {titulo:'Núcleo caudado', termos:['núcleo caudado'], explicacao:'Estrutura profunda relacionada ao corpo estriado.'},
      {titulo:'Putâmen', termos:['putâmen'], explicacao:'Componente lateral dos núcleos da base.'},
      {titulo:'Globo pálido', termos:['globo pálido'], explicacao:'Estrutura medial ao putâmen.'},
      {titulo:'Cápsula interna', termos:['cápsula interna'], explicacao:'Feixe de fibras entre núcleos profundos, clinicamente importante em AVC lacunar.'},
    ],
    pontosResidencia: ['Lesões pequenas na cápsula interna podem produzir déficit motor denso.', 'Núcleos da base aparecem em distúrbios do movimento.'],
    lacunasModelo: [],
  },
  {
    id: 'neuro-cortex-motor-sensitivo',
    titulo: 'Córtex motor e somatossensitivo',
    area: 'neuroanatomia',
    resumo: 'Rota cortical pelas principais áreas primárias.',
    etapas: [
      {titulo:'Giro pré-central', termos:['giro pré-central'], explicacao:'Principal referência anatômica do córtex motor primário.'},
      {titulo:'Giro pós-central', termos:['giro pós-central'], explicacao:'Principal referência anatômica do córtex somatossensitivo primário.'},
      {titulo:'Lóbulo parietal superior', termos:['lóbulo parietal superior'], explicacao:'Integração somatossensitiva associativa.'},
    ],
    pontosResidencia: ['A representação somatotópica é tema clássico.', 'Déficits contralaterais ajudam a localizar lesões corticais.'],
    lacunasModelo: [],
  },
  {
    id: 'neuro-linguagem',
    titulo: 'Áreas corticais da linguagem',
    area: 'neuroanatomia',
    resumo: 'Rota de estudo por giros frontal inferior, supramarginal e angular.',
    etapas: [
      {titulo:'Giro frontal inferior', termos:['giro frontal inferior'], explicacao:'Âncora anatômica da área motora da linguagem no hemisfério dominante.'},
      {titulo:'Giro supramarginal', termos:['giro supramarginal'], explicacao:'Participa da rede perisilviana de linguagem.'},
      {titulo:'Giro angular', termos:['giro angular'], explicacao:'Integra linguagem, leitura e processamento multimodal.'},
    ],
    pontosResidencia: ['Afasias são cobradas por associação entre localização e padrão clínico.', 'O hemisfério dominante é geralmente o esquerdo.'],
    lacunasModelo: [],
  },
  {
    id: 'neuro-limbico',
    titulo: 'Sistema límbico: amígdala e parahipocampo',
    area: 'neuroanatomia',
    resumo: 'Rota profunda voltada a memória e emoção.',
    etapas: [
      {titulo:'Amígdala', termos:['amígdala'], explicacao:'Estrutura temporal medial relacionada a respostas emocionais.'},
      {titulo:'Giro parahipocampal', termos:['giro parahipocampal'], explicacao:'Região medial temporal associada à memória.'},
      {titulo:'Fórnice', termos:['fórnice do prosencéfalo'], explicacao:'Via de conexão límbica importante.'},
    ],
    pontosResidencia: ['Memória episódica e temporal medial são temas recorrentes.', 'Amígdala é associada ao processamento emocional.'],
    lacunasModelo: [],
  },
  {
    id: 'neuro-tronco-encefalico',
    titulo: 'Tronco encefálico',
    area: 'neuroanatomia',
    resumo: 'Sequência craniocaudal para orientação em neurologia.',
    etapas: [
      {titulo:'Mesencéfalo', termos:['mesencéfalo'], explicacao:'Porção superior do tronco encefálico.'},
      {titulo:'Ponte e região pontina', termos:['ponte', 'pons'], explicacao:'Porção média; use conceitos disponíveis de tronco encefálico quando a ponte não estiver isolada.'},
      {titulo:'Bulbo e transição medular', termos:['medula oblonga', 'bulbo'], explicacao:'Porção inferior e transição para medula espinhal.'},
    ],
    pontosResidencia: ['Síndromes alternas ajudam a localizar lesões do tronco.', 'Associe pares cranianos à altura aproximada de emergência.'],
    lacunasModelo: ['Algumas subdivisões do tronco podem não estar isoladas no catálogo traduzido; o sistema usa o melhor conceito relacionado disponível.'],
  },
  {
    id: 'neuro-oculomotores',
    titulo: 'Nervos oculomotor, troclear e movimentos oculares',
    area: 'neuroanatomia',
    resumo: 'Integra nervos cranianos com músculos extrínsecos do olho.',
    etapas: [
      {titulo:'Nervo oculomotor', termos:['nervo oculomotor', 'ramo superior do nervo oculomotor', 'ramo inferior do nervo oculomotor'], explicacao:'Principal nervo motor extrínseco do olho.'},
      {titulo:'Nervo troclear', termos:['nervo troclear'], explicacao:'Inerva o oblíquo superior.'},
      {titulo:'Retos ocular', termos:['superior reto', 'inferior reto', 'medial reto', 'lateral reto'], explicacao:'Use os músculos retos como âncoras funcionais.'},
    ],
    pontosResidencia: ['III, IV e VI são cobrados em diplopia e paresias oculares.', 'Reto lateral é VI; oblíquo superior é IV; os demais principais são III.'],
    lacunasModelo: ['O nervo abducente pode não estar segmentado nesta versão da base; a função é ensinada pela anatomia muscular associada.'],
  },
  {
    id: 'neuro-trigeminal-v1',
    titulo: 'Trigêmeo: divisão oftálmica (V1)',
    area: 'neuroanatomia',
    resumo: 'Percurso craniano disponível da divisão oftálmica e seus ramos.',
    etapas: [
      {titulo:'Nervo oftálmico', termos:['nervo oftálmico'], explicacao:'Primeira divisão sensitiva do trigêmeo.'},
      {titulo:'Nervo frontal', termos:['nervo frontal'], explicacao:'Ramo de V1.'},
      {titulo:'Nervo lacrimal', termos:['nervo lacrimal'], explicacao:'Ramo de V1 relacionado à órbita.'},
      {titulo:'Nervo nasociliar', termos:['nervo nasociliar'], explicacao:'Ramo de V1 com múltiplas divisões orbitárias.'},
    ],
    pontosResidencia: ['V1 participa da aferência do reflexo corneano.', 'Dor e sensibilidade da fronte/orbita são correlações comuns.'],
    lacunasModelo: [],
  },
  {
    id: 'neuro-nervo-optico',
    titulo: 'Nervo óptico e órbita',
    area: 'neuroanatomia',
    resumo: 'Rota visual entre globo ocular e nervo óptico.',
    etapas: [
      {titulo:'Globo ocular', termos:['globo ocular', 'olho do lado direito'], explicacao:'Órgão receptor visual.'},
      {titulo:'Nervo óptico', termos:['nervo óptico'], explicacao:'Via aferente principal da visão.'},
    ],
    pontosResidencia: ['Lesões do nervo óptico produzem perda visual monocular.', 'Aferência do reflexo fotomotor é pelo II par.'],
    lacunasModelo: [],
  },
  {
    id: 'neuro-cerebelo-coordenacao',
    titulo: 'Cerebelo e coordenação',
    area: 'neuroanatomia',
    resumo: 'Rota de revisão de estruturas posteriores relacionadas à coordenação motora.',
    etapas: [
      {titulo:'Cerebelo', termos:['cerebelo'], explicacao:'Estrutura de coordenação e ajuste motor.'},
      {titulo:'Tronco encefálico', termos:['mesencéfalo', 'segmento do mesencéfalo'], explicacao:'Use o tronco como relação anatômica anterior.'},
    ],
    pontosResidencia: ['Ataxia, dismetria e tremor de intenção apontam para disfunção cerebelar.', 'Sinais cerebelares tendem a ser ipsilaterais.'],
    lacunasModelo: ['A segmentação fina de pedúnculos cerebelares pode não estar disponível como malhas independentes.'],
  },
  {
    id: 'arterial-aorta',
    titulo: 'Aorta: ascendente, arco e descendente',
    area: 'arterial',
    resumo: 'Rota longitudinal do principal vaso sistêmico.',
    etapas: [
      {titulo:'Aorta ascendente', termos:['ascendente aorta'], explicacao:'Saída do ventrículo esquerdo.'},
      {titulo:'Arco aórtico', termos:['arco da aorta'], explicacao:'Transição para a aorta descendente e origem de ramos supraaórticos.'},
      {titulo:'Aorta torácica descendente', termos:['descendente torácico aorta', 'descendente aorta'], explicacao:'Porção torácica posterior.'},
      {titulo:'Aorta abdominal', termos:['aorta abdominal'], explicacao:'Porção abaixo do diafragma.'},
    ],
    pontosResidencia: ['Dissecção e aneurisma exigem localização por segmento.', 'O arco e a bifurcação abdominal são marcos de alto rendimento.'],
    lacunasModelo: [],
  },
  {
    id: 'arterial-carotida',
    titulo: 'Eixo carotídeo',
    area: 'arterial',
    resumo: 'Rota arterial para cabeça e pescoço.',
    etapas: [
      {titulo:'Carótida interna', termos:['artéria carótida interna'], explicacao:'Continuação para circulação intracraniana.'},
      {titulo:'Círculo cerebral', termos:['cerebral arterial círculo'], explicacao:'Destino intracraniano principal.'},
    ],
    pontosResidencia: ['Doença carotídea associa-se a AIT e AVC.', 'Bifurcação e seio carotídeo são conceitos clássicos.'],
    lacunasModelo: ['A carótida comum/externa pode não estar completamente isolada no conjunto atual.'],
  },
  {
    id: 'arterial-subclavia-axilar-braquial',
    titulo: 'Subclávia → axilar → braquial',
    area: 'arterial',
    resumo: 'Percurso arterial proximal do membro superior.',
    etapas: [
      {titulo:'Subclávia', termos:['artéria subclávio'], explicacao:'Vaso de transição cervicotorácica.'},
      {titulo:'Axila', termos:['veia axilar', 'artéria braquial'], explicacao:'Use cintura escapular e continuidade vascular como referência quando a artéria axilar não estiver isolada.'},
      {titulo:'Braquial', termos:['artéria braquial'], explicacao:'Principal artéria do braço.'},
    ],
    pontosResidencia: ['A continuidade anatômica muda de nome ao cruzar marcos ósseos/musculares.', 'A braquial é referência de pressão arterial e fossa cubital.'],
    lacunasModelo: ['A artéria axilar pode não aparecer com nomenclatura isolada estável; a rota usa estruturas adjacentes.'],
  },
  {
    id: 'arterial-radial-ulnar',
    titulo: 'Braquial → radial e ulnar',
    area: 'arterial',
    resumo: 'Rota distal do suprimento arterial do antebraço.',
    etapas: [
      {titulo:'Braquial', termos:['artéria braquial'], explicacao:'Vaso proximal.'},
      {titulo:'Radial', termos:['artéria radial'], explicacao:'Ramo lateral do antebraço.'},
      {titulo:'Ulnar', termos:['artéria ulnar'], explicacao:'Ramo medial do antebraço.'},
    ],
    pontosResidencia: ['Pulso radial é o mais usado na prática.', 'A artéria radial atravessa a tabaqueira anatômica.'],
    lacunasModelo: [],
  },
  {
    id: 'arterial-celiaco',
    titulo: 'Tronco celíaco',
    area: 'arterial',
    resumo: 'Rota do intestino anterior a partir da aorta abdominal.',
    etapas: [
      {titulo:'Aorta abdominal', termos:['aorta abdominal'], explicacao:'Origem proximal.'},
      {titulo:'Tronco celíaco', termos:['celíaco tronco', 'artéria celíaco'], explicacao:'Tronco visceral do intestino anterior.'},
      {titulo:'Órgãos-alvo', termos:['estômago', 'fígado', 'baço'], explicacao:'Âncoras do território irrigado.'},
    ],
    pontosResidencia: ['Ramos clássicos: gástrica esquerda, esplênica e hepática comum.', 'Território do intestino anterior é tema recorrente.'],
    lacunasModelo: ['Nem todos os ramos terminais estão disponíveis como malhas nomeadas.'],
  },
  {
    id: 'arterial-mesenterica-superior',
    titulo: 'Artéria mesentérica superior',
    area: 'arterial',
    resumo: 'Território arterial do intestino médio.',
    etapas: [
      {titulo:'AMS', termos:['artéria mesentérica superior'], explicacao:'Principal artéria do intestino médio.'},
      {titulo:'Jejuno e íleo', termos:['jejuno', 'íleo'], explicacao:'Delgado principal.'},
      {titulo:'Ceco e cólon direito', termos:['ceco', 'ascendente cólon'], explicacao:'Extensão do território distal.'},
    ],
    pontosResidencia: ['Isquemia mesentérica aguda é correlação de alto rendimento.', 'Integre desenvolvimento embrionário e territórios arteriais.'],
    lacunasModelo: [],
  },
  {
    id: 'arterial-mesenterica-inferior',
    titulo: 'Artéria mesentérica inferior',
    area: 'arterial',
    resumo: 'Território arterial do intestino posterior.',
    etapas: [
      {titulo:'AMI', termos:['artéria mesentérica inferior'], explicacao:'Principal vaso do intestino posterior.'},
      {titulo:'Cólon esquerdo', termos:['descendente cólon', 'sigmoide cólon'], explicacao:'Território colônico distal.'},
      {titulo:'Reto superior', termos:['reto'], explicacao:'Âncora distal do território.'},
    ],
    pontosResidencia: ['Zonas de watershed do cólon são relevantes em isquemia.', 'Território do intestino posterior é clássico de prova.'],
    lacunasModelo: [],
  },
  {
    id: 'arterial-renal',
    titulo: 'Artérias renais',
    area: 'arterial',
    resumo: 'Rota da aorta abdominal para os rins.',
    etapas: [
      {titulo:'Aorta abdominal', termos:['aorta abdominal'], explicacao:'Origem.'},
      {titulo:'Artéria renal', termos:['artéria renal'], explicacao:'Vaso principal do rim.'},
      {titulo:'Divisões renais', termos:['divisão anterior da artéria renal', 'segmento da artéria renal'], explicacao:'Segmentação arterial quando disponível.'},
    ],
    pontosResidencia: ['Artérias renais são funcionalmente terminais.', 'Estenose renal e anatomia segmentar têm importância clínica.'],
    lacunasModelo: [],
  },
  {
    id: 'arterial-iliaca-femoral-poplitea',
    titulo: 'Ilíaca → femoral → poplítea',
    area: 'arterial',
    resumo: 'Rota arterial principal do membro inferior.',
    etapas: [
      {titulo:'Ilíaca comum', termos:['artéria ilíaca comum'], explicacao:'Transição da aorta para a pelve/membro inferior.'},
      {titulo:'Femoral', termos:['artéria femoral'], explicacao:'Principal artéria da coxa.'},
      {titulo:'Poplítea', termos:['artéria poplítea'], explicacao:'Continuação posterior ao joelho.'},
      {titulo:'Tibial anterior', termos:['artéria tibial anterior'], explicacao:'Ramo distal demonstrável no atlas.'},
    ],
    pontosResidencia: ['Pulso femoral e poplíteo são referências clínicas.', 'Doença arterial periférica é correlacionada por níveis de obstrução.'],
    lacunasModelo: [],
  },
  {
    id: 'arterial-pulmonar',
    titulo: 'Circulação arterial pulmonar',
    area: 'arterial',
    resumo: 'Rota do tronco/arterias pulmonares até seus ramos segmentares.',
    etapas: [
      {titulo:'Artéria pulmonar', termos:['artéria pulmonar'], explicacao:'Saída do ventrículo direito.'},
      {titulo:'Direita e esquerda', termos:['artéria pulmonar do lado direito', 'artéria pulmonar do lado esquerdo'], explicacao:'Distribuição para cada pulmão.'},
      {titulo:'Ramos segmentares', termos:['artéria pulmonar segmentar', 'artéria pulmonar subsegmentar'], explicacao:'Distribuição intrapulmonar.'},
    ],
    pontosResidencia: ['Embolia pulmonar é interpretada por níveis arteriais.', 'Segmentação pulmonar ajuda a localizar lesões.'],
    lacunasModelo: [],
  },
  {
    id: 'venoso-cavas',
    titulo: 'Veias cavas superior e inferior',
    area: 'venoso',
    resumo: 'Eixos principais de retorno venoso sistêmico.',
    etapas: [
      {titulo:'VCI', termos:['veia cava inferior'], explicacao:'Retorno de abdome, pelve e membros inferiores.'},
      {titulo:'VCS', termos:['veia cava superior'], explicacao:'Retorno de cabeça, pescoço e membros superiores.'},
      {titulo:'Coração', termos:['coração', 'lado direito do coração'], explicacao:'Destino final no átrio direito.'},
    ],
    pontosResidencia: ['Síndromes de VCS/VCI dependem de topografia da obstrução.', 'Integre retorno venoso com circulação sistêmica.'],
    lacunasModelo: [],
  },
  {
    id: 'venoso-azigos',
    titulo: 'Sistema ázigos',
    area: 'venoso',
    resumo: 'Rota de drenagem torácica posterior e colateral cavocaval.',
    etapas: [
      {titulo:'Hemiázigos', termos:['veia hemiázigos'], explicacao:'Drenagem inferior esquerda.'},
      {titulo:'Hemiázigos acessória', termos:['veia hemiázigos acessória'], explicacao:'Drenagem superior esquerda.'},
      {titulo:'Ázigos', termos:['veia ázigos'], explicacao:'Tronco direito que desemboca na VCS.'},
      {titulo:'VCS', termos:['veia cava superior'], explicacao:'Destino superior.'},
    ],
    pontosResidencia: ['É importante como via colateral.', 'A veia ázigos é referência em radiologia torácica.'],
    lacunasModelo: [],
  },
  {
    id: 'venoso-porta',
    titulo: 'Sistema porta hepático',
    area: 'venoso',
    resumo: 'Rota de sangue venoso gastrointestinal para o fígado.',
    etapas: [
      {titulo:'Veia porta', termos:['veia porta', 'veia porta hepática'], explicacao:'Entrada principal hepática.'},
      {titulo:'Ramos portais', termos:['veia porta do lado direito', 'veia porta do lado esquerdo'], explicacao:'Divisão intra-hepática.'},
      {titulo:'Fígado', termos:['fígado'], explicacao:'Órgão de destino antes do retorno sistêmico.'},
    ],
    pontosResidencia: ['Hipertensão portal e suas colaterais são temas essenciais.', 'A veia porta transporta sangue rico em nutrientes e pobre em oxigênio.'],
    lacunasModelo: [],
  },
  {
    id: 'venoso-renais',
    titulo: 'Veias renais e cava inferior',
    area: 'venoso',
    resumo: 'Retorno venoso dos rins à VCI.',
    etapas: [
      {titulo:'Veias renais', termos:['veia renal'], explicacao:'Drenagem de cada rim.'},
      {titulo:'VCI', termos:['veia cava inferior'], explicacao:'Destino venoso.'},
    ],
    pontosResidencia: ['A veia renal esquerda tem relações anatômicas especiais.', 'Síndrome do quebra-nozes é correlação clássica.'],
    lacunasModelo: [],
  },
  {
    id: 'venoso-iliaco-femoral',
    titulo: 'Femoral → ilíaca → VCI',
    area: 'venoso',
    resumo: 'Rota de retorno venoso profundo do membro inferior.',
    etapas: [
      {titulo:'Femoral', termos:['veia femoral'], explicacao:'Veia profunda da coxa.'},
      {titulo:'Ilíaca comum', termos:['veia ilíaca comum'], explicacao:'Convergência pélvica.'},
      {titulo:'VCI', termos:['veia cava inferior'], explicacao:'Destino abdominal.'},
    ],
    pontosResidencia: ['TVP proximal envolve veias femorais/ilíacas.', 'Conhecer continuidade ajuda em ultrassom vascular.'],
    lacunasModelo: [],
  },
  {
    id: 'venoso-pulmonar',
    titulo: 'Veias pulmonares',
    area: 'venoso',
    resumo: 'Rota do retorno oxigenado dos pulmões ao coração esquerdo.',
    etapas: [
      {titulo:'Veias segmentares', termos:['veia pulmonar segmentar', 'veia pulmonar subsegmentar'], explicacao:'Coleta intrapulmonar.'},
      {titulo:'Veias superiores/inferiores', termos:['veia pulmonar superior', 'veia pulmonar inferior'], explicacao:'Troncos principais.'},
      {titulo:'Coração esquerdo', termos:['lado esquerdo do coração'], explicacao:'Destino no átrio esquerdo.'},
    ],
    pontosResidencia: ['Veias pulmonares carregam sangue oxigenado.', 'Ablação de fibrilação atrial usa óstios pulmonares como referência anatômica.'],
    lacunasModelo: [],
  },
  {
    id: 'linfatico-timo',
    titulo: 'Timo e imunidade',
    area: 'linfatico',
    resumo: 'Rota do timo no mediastino anterior.',
    etapas: [
      {titulo:'Timo', termos:['timo', 'lobo do timo'], explicacao:'Órgão linfoide primário.'},
      {titulo:'Mediastino anterior', termos:['anterior mediastino', 'superior mediastino'], explicacao:'Contexto topográfico.'},
    ],
    pontosResidencia: ['Maturação de linfócitos T ocorre no timo.', 'Timoma é diagnóstico diferencial de massa mediastinal anterior.'],
    lacunasModelo: [],
  },
  {
    id: 'linfatico-baco',
    titulo: 'Baço e sistema linfático',
    area: 'linfatico',
    resumo: 'Rota do maior órgão linfoide secundário abdominal.',
    etapas: [
      {titulo:'Baço', termos:['baço'], explicacao:'Órgão linfoide secundário.'},
      {titulo:'Estômago e diafragma', termos:['estômago', 'diafragma'], explicacao:'Relações topográficas úteis.'},
    ],
    pontosResidencia: ['Filtra sangue, não linfa.', 'Trauma esplênico e asplenia têm grande importância clínica.'],
    lacunasModelo: [],
  },
  {
    id: 'linfatico-drenagem-mama',
    titulo: 'Drenagem linfática da mama',
    area: 'linfatico',
    resumo: 'Rota conceitual para revisão de linfonodos axilares e cadeia mamária interna.',
    etapas: [
      {titulo:'Axila', termos:['veia axilar', 'clavícula'], explicacao:'Âncora topográfica para cadeias axilares.'},
      {titulo:'Parede torácica', termos:['tórax', 'anterior tórax'], explicacao:'Âncora para drenagem parasterna.'},
    ],
    pontosResidencia: ['A maior parte da drenagem mamária segue para linfonodos axilares.', 'Linfonodo sentinela é conceito central em câncer de mama.'],
    lacunasModelo: ['Linfonodos axilares e mamários internos não estão segmentados como malhas individuais na base atual; a rota usa âncoras topográficas.'],
  },
  {
    id: 'linfatico-cervical',
    titulo: 'Cadeias cervicais e drenagem de cabeça/pescoço',
    area: 'linfatico',
    resumo: 'Rota conceitual de drenagem cervical profunda e superficial.',
    etapas: [
      {titulo:'Pescoço', termos:['tireoide', 'laringe', 'faringe'], explicacao:'Âncoras viscerais cervicais.'},
      {titulo:'Carótida interna', termos:['artéria carótida interna'], explicacao:'Âncora para cadeia jugulocarotídea profunda.'},
    ],
    pontosResidencia: ['Metástases cervicais seguem padrões por níveis linfonodais.', 'Cabeça e pescoço exigem integração entre drenagem e sítio primário.'],
    lacunasModelo: ['A base não contém cadeias cervicais linfonodais completas como malhas separadas.'],
  },
  {
    id: 'linfatico-pelve-retroperitonio',
    titulo: 'Drenagem linfática pélvica e retroperitoneal',
    area: 'linfatico',
    resumo: 'Rota conceitual para oncologia urológica e pélvica.',
    etapas: [
      {titulo:'Vasos ilíacos', termos:['artéria ilíaca comum', 'veia ilíaca comum'], explicacao:'Âncoras dos principais grupos pélvicos.'},
      {titulo:'Aorta/VCI', termos:['aorta abdominal', 'veia cava inferior'], explicacao:'Âncoras para cadeias para-aórticas e retroperitoneais.'},
      {titulo:'Órgãos pélvicos', termos:['próstata', 'bexiga urinária', 'testículo'], explicacao:'Órgãos-alvo para correlação de drenagem.'},
    ],
    pontosResidencia: ['Testículo drena para cadeias retroperitoneais, não para inguinais superficiais.', 'Órgãos pélvicos têm drenagem ilíaca complexa.'],
    lacunasModelo: ['Linfonodos não estão detalhados como malhas nesta fonte; o atlas usa os grandes vasos como eixos anatômicos.'],
  },
  {
    id: 'periferico-plexo-braquial',
    titulo: 'Plexo braquial',
    area: 'nervos-perifericos',
    resumo: 'Rota conceitual do plexo braquial usando cintura escapular e vasos axilares como âncoras.',
    etapas: [
      {titulo:'Raiz cervical/saída do pescoço', termos:['clavícula', 'artéria subclávio'], explicacao:'Âncora cervicotorácica.'},
      {titulo:'Axila', termos:['veia axilar', 'escápula'], explicacao:'Passagem para o membro superior.'},
      {titulo:'Braço', termos:['úmero', 'artéria braquial'], explicacao:'Distribuição distal.'},
    ],
    pontosResidencia: ['Lesões por troncos/cordões produzem padrões motores e sensitivos característicos.', 'Erb-Duchenne e Klumpke são síndromes clássicas.'],
    lacunasModelo: ['A base não contém o plexo braquial completo como malhas nervosas periféricas; a rota é topográfica e conceitual.'],
  },
  {
    id: 'periferico-mediano',
    titulo: 'Nervo mediano',
    area: 'nervos-perifericos',
    resumo: 'Rota conceitual do braço ao túnel do carpo.',
    etapas: [
      {titulo:'Braço medial', termos:['artéria braquial', 'úmero'], explicacao:'Âncora proximal do trajeto.'},
      {titulo:'Fossa cubital', termos:['artéria braquial', 'veia cubital mediano'], explicacao:'Âncora no cotovelo.'},
      {titulo:'Antebraço flexor', termos:['cabeça umeral do pronador redondo', 'flexor do carpo radial'], explicacao:'Âncoras musculares.'},
      {titulo:'Túnel do carpo', termos:['flexor retináculo do punho', 'osso do carpo'], explicacao:'Ponto compressivo clássico.'},
    ],
    pontosResidencia: ['Síndrome do túnel do carpo é a correlação mais frequente.', 'Lesão proximal também compromete pronação e flexores.'],
    lacunasModelo: ['O nervo mediano não existe como malha periférica contínua na base atual.'],
  },
  {
    id: 'periferico-ulnar',
    titulo: 'Nervo ulnar',
    area: 'nervos-perifericos',
    resumo: 'Rota conceitual medial do braço ao punho.',
    etapas: [
      {titulo:'Braço medial', termos:['úmero', 'artéria braquial'], explicacao:'Âncora proximal.'},
      {titulo:'Cotovelo medial', termos:['artéria colateral ulnar superior', 'ulna'], explicacao:'Região do epicôndilo medial.'},
      {titulo:'Antebraço ulnar', termos:['flexor do carpo ulnar', 'artéria ulnar'], explicacao:'Trajeto distal.'},
    ],
    pontosResidencia: ['Compressão no cotovelo pode gerar parestesias em 4º/5º dedos.', 'Lesão ulnar compromete interósseos e força intrínseca da mão.'],
    lacunasModelo: ['O nervo ulnar não está segmentado como malha contínua.'],
  },
  {
    id: 'periferico-radial',
    titulo: 'Nervo radial',
    area: 'nervos-perifericos',
    resumo: 'Rota conceitual posterior do braço e lateral do antebraço.',
    etapas: [
      {titulo:'Úmero', termos:['úmero', 'artéria braquial profunda'], explicacao:'Âncora do sulco radial.'},
      {titulo:'Cotovelo lateral', termos:['artéria colateral radial', 'rádio'], explicacao:'Transição para antebraço.'},
      {titulo:'Compartimento extensor', termos:['extensor do carpo radial longo', 'extensor do carpo radial curto'], explicacao:'Âncoras funcionais.'},
    ],
    pontosResidencia: ['Lesão radial clássica causa queda do punho.', 'Fratura da diáfise do úmero é correlação frequente.'],
    lacunasModelo: ['O nervo radial periférico não está disponível como malha contínua.'],
  },
  {
    id: 'periferico-femoral',
    titulo: 'Nervo femoral',
    area: 'nervos-perifericos',
    resumo: 'Rota conceitual da pelve ao triângulo femoral.',
    etapas: [
      {titulo:'Pelve/ilíacos', termos:['artéria ilíaca comum', 'pelve'], explicacao:'Âncora proximal.'},
      {titulo:'Triângulo femoral', termos:['artéria femoral', 'veia femoral', 'sartório'], explicacao:'Âncora de passagem abaixo do ligamento inguinal.'},
      {titulo:'Coxa anterior', termos:['reto femoral', 'fêmur'], explicacao:'Âncora motora do quadríceps.'},
    ],
    pontosResidencia: ['Lesão femoral compromete extensão do joelho.', 'Reflexo patelar envolve L3-L4/femoral.'],
    lacunasModelo: ['O nervo femoral não está isolado como malha nesta base.'],
  },
  {
    id: 'periferico-ciatico',
    titulo: 'Nervo ciático',
    area: 'nervos-perifericos',
    resumo: 'Rota conceitual da região glútea à fossa poplítea.',
    etapas: [
      {titulo:'Região glútea', termos:['glúteo médio', 'fêmur'], explicacao:'Âncora proximal.'},
      {titulo:'Coxa posterior', termos:['fêmur', 'adutor magno'], explicacao:'Trajeto posterior profundo.'},
      {titulo:'Fossa poplítea', termos:['artéria poplítea', 'veia poplítea'], explicacao:'Região de divisão terminal.'},
    ],
    pontosResidencia: ['Hérnia discal lombossacra pode produzir ciatalgia.', 'Injeções glúteas devem evitar trajetos neurovasculares.'],
    lacunasModelo: ['O nervo ciático não está segmentado como malha periférica na base atual.'],
  },
  {
    id: 'periferico-tibial',
    titulo: 'Nervo tibial',
    area: 'nervos-perifericos',
    resumo: 'Rota conceitual posterior da perna e tornozelo.',
    etapas: [
      {titulo:'Fossa poplítea', termos:['artéria poplítea', 'veia poplítea'], explicacao:'Origem distal após divisão ciática.'},
      {titulo:'Perna posterior', termos:['tíbia', 'tendão calcâneo'], explicacao:'Âncoras posteriores.'},
      {titulo:'Retropé', termos:['calcâneo', 'osso do tarso'], explicacao:'Âncora distal.'},
    ],
    pontosResidencia: ['Lesão tibial compromete flexão plantar e sensibilidade plantar.', 'Túnel do tarso é correlação compressiva.'],
    lacunasModelo: ['O nervo tibial não está disponível como malha contínua.'],
  },
  {
    id: 'periferico-fibular-comum',
    titulo: 'Nervo fibular comum',
    area: 'nervos-perifericos',
    resumo: 'Rota conceitual lateral do joelho e perna.',
    etapas: [
      {titulo:'Fossa poplítea', termos:['artéria poplítea', 'fíbula'], explicacao:'Âncora proximal.'},
      {titulo:'Colo da fíbula', termos:['fíbula'], explicacao:'Ponto superficial clássico de lesão.'},
      {titulo:'Compartimento anterior/lateral', termos:['tibial anterior', 'fibular longo', 'fibular curto'], explicacao:'Âncoras motoras distais.'},
    ],
    pontosResidencia: ['Lesão no colo da fíbula pode causar pé caído.', 'Ramo profundo relaciona-se a dorsiflexores; superficial a eversores.'],
    lacunasModelo: ['O nervo fibular comum não está isolado como malha nervosa.'],
  },
  {
    id: 'periferico-obturatorio',
    titulo: 'Nervo obturatório',
    area: 'nervos-perifericos',
    resumo: 'Rota conceitual da pelve ao compartimento medial da coxa.',
    etapas: [
      {titulo:'Pelve', termos:['pelve', 'artéria ilíaca comum'], explicacao:'Âncora proximal.'},
      {titulo:'Coxa medial', termos:['adutor longo', 'adutor curto', 'adutor magno'], explicacao:'Âncoras funcionais.'},
    ],
    pontosResidencia: ['Lesão obturatória compromete adução da coxa.', 'É relevante em cirurgia pélvica e hérnia obturatória.'],
    lacunasModelo: ['O nervo obturatório não está segmentado como malha.'],
  },
  {
    id: 'periferico-nervo-optico',
    titulo: 'Nervo óptico (II)',
    area: 'nervos-perifericos',
    resumo: 'Rota craniana sensitiva especializada disponível diretamente no atlas.',
    etapas: [
      {titulo:'Olho', termos:['globo ocular', 'olho do lado direito'], explicacao:'Origem funcional.'},
      {titulo:'Nervo óptico', termos:['nervo óptico'], explicacao:'Trajeto orbitário/craniano disponível.'},
    ],
    pontosResidencia: ['Aferência do reflexo fotomotor.', 'Lesão pré-quiasmática causa perda monocular.'],
    lacunasModelo: [],
  },
  {
    id: 'esp-cirurgia-geral-abdome',
    titulo: 'Cirurgia Geral: abdome de alta incidência',
    area: 'especialidades',
    resumo: 'Roteiro integrado de marcos mais cobrados em cirurgia geral.',
    especialidade: 'Cirurgia Geral',
    etapas: [
      {titulo:'Parede abdominal/Hesselbach', termos:['artéria epigástrica inferior', 'parede abdominal anterior'], explicacao:'Hérnias inguinais.'},
      {titulo:'Vias biliares', termos:['vesícula biliar', 'ducto cístico', 'ducto hepático comum'], explicacao:'Colecistite e colecistectomia.'},
      {titulo:'Apêndice', termos:['apêndice vermiforme', 'ceco'], explicacao:'Apendicite.'},
      {titulo:'Pâncreas/duodeno', termos:['pâncreas', 'duodeno'], explicacao:'Pancreatite e cirurgia pancreatoduodenal.'},
    ],
    pontosResidencia: ['Integre anatomia a casos de abdome agudo.', 'Hesselbach, Calot e apêndice são marcos de prova recorrentes.'],
    lacunasModelo: [],
  },
  {
    id: 'esp-cardiologia',
    titulo: 'Cardiologia: coração, coronárias e grandes vasos',
    area: 'especialidades',
    resumo: 'Roteiro anatômico para cardiologia e emergência cardiovascular.',
    especialidade: 'Cardiologia',
    etapas: [
      {titulo:'Coração', termos:['coração'], explicacao:'Câmaras e parede.'},
      {titulo:'Coronárias', termos:['coronária', 'coronary'], explicacao:'Irrigação miocárdica.'},
      {titulo:'Aorta', termos:['aorta', 'arco da aorta'], explicacao:'Saída sistêmica.'},
      {titulo:'Cavas', termos:['veia cava superior', 'veia cava inferior'], explicacao:'Retorno sistêmico.'},
    ],
    pontosResidencia: ['Associe territórios coronários a ECG/infarto.', 'Grandes vasos ajudam em choque, dissecção e cardiopatias estruturais.'],
    lacunasModelo: [],
  },
  {
    id: 'esp-neurologia',
    titulo: 'Neurologia: córtex, núcleos profundos e circulação cerebral',
    area: 'especialidades',
    resumo: 'Roteiro de localização neurológica para residência.',
    especialidade: 'Neurologia',
    etapas: [
      {titulo:'Córtex motor/sensitivo', termos:['giro pré-central', 'giro pós-central'], explicacao:'Déficits corticais.'},
      {titulo:'Cápsula interna', termos:['cápsula interna'], explicacao:'Déficits motores densos.'},
      {titulo:'Núcleos da base', termos:['núcleo caudado', 'putâmen', 'globo pálido'], explicacao:'Distúrbios do movimento.'},
      {titulo:'Willis', termos:['cerebral arterial círculo'], explicacao:'AVC e aneurismas.'},
    ],
    pontosResidencia: ['Pratique localizar déficit pelo território e pela anatomia.', 'A cápsula interna é pequeno local com grande impacto clínico.'],
    lacunasModelo: [],
  },
  {
    id: 'esp-neurocirurgia',
    titulo: 'Neurocirurgia: base do crânio e neurovascular',
    area: 'especialidades',
    resumo: 'Roteiro de estruturas profundas e vasos da base.',
    especialidade: 'Neurocirurgia',
    etapas: [
      {titulo:'Órbita/nervo óptico', termos:['nervo óptico', 'globo ocular'], explicacao:'Via visual anterior.'},
      {titulo:'Trigêmeo V1', termos:['nervo oftálmico', 'nervo nasociliar'], explicacao:'Base craniana anterior/orbitária.'},
      {titulo:'Circulação cerebral', termos:['artéria carótida interna', 'artéria comunicante posterior', 'artéria cerebral anterior'], explicacao:'Marcos aneurismáticos.'},
    ],
    pontosResidencia: ['Integre pares cranianos com circulação da base.', 'Rotas são didáticas e não substituem planejamento cirúrgico.'],
    lacunasModelo: ['A geometria da base não é um modelo neurocirúrgico de alta resolução.'],
  },
  {
    id: 'esp-ortopedia-membro-superior',
    titulo: 'Ortopedia: ombro, cotovelo e punho',
    area: 'especialidades',
    resumo: 'Roteiro osteomuscular de alto rendimento do membro superior.',
    especialidade: 'Ortopedia',
    etapas: [
      {titulo:'Manguito rotador', termos:['supraespinal', 'infraespinal', 'subescapular', 'redondo menor'], explicacao:'Ombro.'},
      {titulo:'Fossa cubital', termos:['artéria braquial', 'rádio', 'ulna'], explicacao:'Cotovelo.'},
      {titulo:'Túnel do carpo', termos:['flexor retináculo do punho', 'osso do carpo'], explicacao:'Punho.'},
    ],
    pontosResidencia: ['Manguito rotador e túnel do carpo são tópicos recorrentes.', 'Use ossos como âncoras para fraturas e relações neurovasculares.'],
    lacunasModelo: [],
  },
  {
    id: 'esp-ortopedia-membro-inferior',
    titulo: 'Ortopedia: quadril, joelho, tornozelo e pé',
    area: 'especialidades',
    resumo: 'Roteiro osteomuscular do membro inferior.',
    especialidade: 'Ortopedia',
    etapas: [
      {titulo:'Quadril/coxa', termos:['fêmur', 'glúteo médio'], explicacao:'Região proximal.'},
      {titulo:'Joelho', termos:['patela', 'reto femoral', 'tíbia'], explicacao:'Mecanismo extensor.'},
      {titulo:'Fossa poplítea', termos:['artéria poplítea', 'veia poplítea'], explicacao:'Relação posterior.'},
      {titulo:'Aquiles/retropé', termos:['tendão calcâneo', 'calcâneo'], explicacao:'Tornozelo posterior.'},
    ],
    pontosResidencia: ['Patela, fêmur proximal e Aquiles são marcos frequentes.', 'Associe nervos periféricos por rotas conceituais quando a malha não existir.'],
    lacunasModelo: [],
  },
  {
    id: 'esp-vascular',
    titulo: 'Cirurgia vascular: eixos arteriais e venosos',
    area: 'especialidades',
    resumo: 'Roteiro longitudinal dos principais eixos vasculares.',
    especialidade: 'Cirurgia Vascular',
    etapas: [
      {titulo:'Aorta abdominal', termos:['aorta abdominal'], explicacao:'Eixo central.'},
      {titulo:'Ilíaca/femoral', termos:['artéria ilíaca comum', 'artéria femoral'], explicacao:'Membro inferior proximal.'},
      {titulo:'Poplítea/tibial', termos:['artéria poplítea', 'artéria tibial anterior'], explicacao:'Membro inferior distal.'},
      {titulo:'Sistema venoso profundo', termos:['veia femoral', 'veia ilíaca comum', 'veia cava inferior'], explicacao:'Retorno profundo.'},
    ],
    pontosResidencia: ['Use a rota para localizar doença arterial periférica e TVP.', 'A base arterial/venosa é uma das partes mais detalhadas deste atlas.'],
    lacunasModelo: [],
  },
  {
    id: 'esp-urologia',
    titulo: 'Urologia: rim, ureter, bexiga e próstata',
    area: 'especialidades',
    resumo: 'Roteiro do trato urinário e pelve masculina.',
    especialidade: 'Urologia',
    etapas: [
      {titulo:'Rim/pedículo', termos:['rim', 'artéria renal', 'veia renal'], explicacao:'Trato superior.'},
      {titulo:'Ureter', termos:['ureter'], explicacao:'Condução urinária.'},
      {titulo:'Bexiga', termos:['bexiga urinária'], explicacao:'Reservatório pélvico.'},
      {titulo:'Próstata/uretra', termos:['próstata', 'uretra'], explicacao:'Saída urinária masculina.'},
    ],
    pontosResidencia: ['Nefrolitíase, hidronefrose e HPB dependem da anatomia do trajeto urinário.', 'Integre relações vasculares do rim.'],
    lacunasModelo: [],
  },
  {
    id: 'esp-otorrino',
    titulo: 'Otorrinolaringologia: via aérea superior',
    area: 'especialidades',
    resumo: 'Roteiro cervical e aerodigestivo para otorrino.',
    especialidade: 'Otorrinolaringologia',
    etapas: [
      {titulo:'Faringe', termos:['faringe'], explicacao:'Conduto comum aerodigestivo.'},
      {titulo:'Laringe', termos:['laringe'], explicacao:'Proteção de via aérea/fonação.'},
      {titulo:'Traqueia', termos:['traqueia'], explicacao:'Continuidade respiratória.'},
      {titulo:'Tireoide', termos:['tireoide'], explicacao:'Relação cervical anterior.'},
    ],
    pontosResidencia: ['Via aérea, deglutição e massas cervicais são temas centrais.', 'Anatomia detalhada dos nervos laríngeos não está completa nesta base.'],
    lacunasModelo: [],
  },
  {
    id: 'esp-cirurgia-toracica',
    titulo: 'Cirurgia torácica: hilo e mediastino',
    area: 'especialidades',
    resumo: 'Roteiro para pulmões, hilo e mediastino.',
    especialidade: 'Cirurgia Torácica',
    etapas: [
      {titulo:'Mediastino', termos:['anterior mediastino', 'superior mediastino'], explicacao:'Compartimentos centrais.'},
      {titulo:'Hilo pulmonar', termos:['principal brônquio', 'artéria pulmonar', 'veia pulmonar superior'], explicacao:'Pedículo pulmonar.'},
      {titulo:'Pulmões', termos:['pulmão do lado direito', 'pulmão do lado esquerdo'], explicacao:'Órgãos-alvo.'},
    ],
    pontosResidencia: ['RALS e relações hilares são clássicas.', 'Mediastino é base do diagnóstico diferencial de massas.'],
    lacunasModelo: [],
  },
  {
    id: 'esp-emergencia',
    titulo: 'Emergência: acessos e marcos vasculares',
    area: 'especialidades',
    resumo: 'Roteiro de anatomia prática para emergência e procedimentos.',
    especialidade: 'Medicina de Emergência',
    etapas: [
      {titulo:'Carótida/pescoço', termos:['artéria carótida interna', 'traqueia'], explicacao:'Via aérea e vasos cervicais.'},
      {titulo:'Fossa cubital', termos:['artéria braquial', 'veia cubital mediano'], explicacao:'Acesso periférico e pulso.'},
      {titulo:'Femoral', termos:['artéria femoral', 'veia femoral'], explicacao:'Acesso vascular proximal.'},
      {titulo:'Poplítea/tibial', termos:['artéria poplítea', 'artéria tibial anterior'], explicacao:'Avaliação vascular distal.'},
    ],
    pontosResidencia: ['Identificação rápida de pulsos e eixos vasculares ajuda em choque e trauma.', 'A aplicação é educacional e não deve orientar procedimento real.'],
    lacunasModelo: [],
  },
  {
    id: 'esp-radiologia',
    titulo: 'Radiologia: eixos de orientação anatômica',
    area: 'especialidades',
    resumo: 'Roteiro macroscópico para correlacionar estruturas em TC/RM.',
    especialidade: 'Radiologia',
    etapas: [
      {titulo:'Mediastino', termos:['aorta', 'veia cava superior', 'traqueia', 'esôfago'], explicacao:'Centro do tórax.'},
      {titulo:'Retroperitônio', termos:['aorta abdominal', 'veia cava inferior', 'rim'], explicacao:'Centro do abdome posterior.'},
      {titulo:'Pelve', termos:['bexiga urinária', 'próstata', 'artéria ilíaca comum'], explicacao:'Centro pélvico.'},
      {titulo:'Encéfalo', termos:['giro pré-central', 'cápsula interna', 'núcleo caudado'], explicacao:'Referências neurológicas.'},
    ],
    pontosResidencia: ['Treine reconhecer relações, não apenas estruturas isoladas.', 'A geometria 3D ajuda a construir mapa espacial para leitura seccional.'],
    lacunasModelo: [],
  },
];

export function resolverRotasEstudoAvancado(indice: ConceitoIndexado[]): RotaEstudoResolvida[] { return ROTAS_ESTUDO_AVANCADO.map(rota=>{ const etapas=rota.etapas.map(etapa=>({...etapa,conceitos:localizar(indice,etapa.termos)})); const ids=new Set(etapas.flatMap(e=>e.conceitos.map(c=>c.conceito.id))); return {...rota,etapas,totalConceitos:ids.size}; }); }

export function filtrarRotas(rotas: RotaEstudoResolvida[], area: AreaEstudoAvancado | 'todas', consulta: string): RotaEstudoResolvida[] { const termo=normalizar(consulta); return rotas.filter(rota => (area==='todas'||rota.area===area) && (!termo || normalizar([rota.titulo,rota.resumo,rota.especialidade,...rota.pontosResidencia,...rota.etapas.flatMap(e=>[e.titulo,e.explicacao,...e.termos])].filter(Boolean).join(' ')).includes(termo))); }
